project_id = "nobtbymxudlcsyurbopl"

[auth.email]
enable_signup = true
enable_confirmations = true

[functions.kiwify-webhook]
verify_jwt = false

[functions.communication-copilot]
verify_jwt = true

[functions.communication-push]
verify_jwt = true

[functions.communication-channel-send]
verify_jwt = true

[functions.communication-channel-webhook]
verify_jwt = false
