BEGIN;

CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;
SET LOCAL search_path = public, extensions;
SELECT no_plan();

SELECT ok(NOT has_table_privilege(client_role, c.oid, privilege),
  client_role || ' has no ' || privilege || ' on public.' || c.relname)
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
CROSS JOIN unnest(ARRAY['anon', 'authenticated']) client_role
CROSS JOIN unnest(ARRAY['TRUNCATE', 'TRIGGER', 'REFERENCES']) privilege
WHERE n.nspname = 'public' AND c.relkind IN ('r', 'p');

SELECT ok(NOT has_table_privilege('anon', c.oid, privilege),
  'anon has no ' || privilege || ' on public.' || c.relname)
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
CROSS JOIN unnest(ARRAY['SELECT', 'INSERT', 'UPDATE', 'DELETE']) privilege
WHERE n.nspname = 'public' AND c.relkind IN ('r', 'p', 'v', 'm', 'f');

SELECT ok(has_table_privilege('authenticated', relation, privilege),
  'authenticated keeps ' || privilege || ' on ' || relation)
FROM (VALUES
  ('public.profiles', 'SELECT'), ('public.profiles', 'INSERT'), ('public.profiles', 'UPDATE'),
  ('public.organizations', 'SELECT'), ('public.organizations', 'UPDATE'),
  ('public.organization_members', 'SELECT'),
  ('public.permissions', 'SELECT'), ('public.role_permissions', 'SELECT'),
  ('public.clients', 'SELECT'), ('public.clients', 'INSERT'), ('public.clients', 'UPDATE'),
  ('public.processes', 'SELECT'), ('public.processes', 'INSERT'), ('public.processes', 'UPDATE'),
  ('public.tasks', 'SELECT'), ('public.tasks', 'INSERT'), ('public.tasks', 'UPDATE'),
  ('public.documents', 'SELECT'), ('public.documents', 'INSERT'), ('public.documents', 'UPDATE'),
  ('public.monitoring_items', 'SELECT'), ('public.monitoring_items', 'INSERT'), ('public.monitoring_items', 'UPDATE'),
  ('public.service_types', 'SELECT'), ('public.service_types', 'INSERT'), ('public.service_types', 'UPDATE'),
  ('public.financial_transactions', 'SELECT'),
  ('public.communication_threads', 'SELECT')
) required(relation, privilege);

SELECT ok(NOT has_table_privilege('authenticated', relation, privilege),
  'authenticated cannot directly ' || privilege || ' ' || relation)
FROM (VALUES
  ('public.permissions', 'INSERT'), ('public.permissions', 'UPDATE'), ('public.permissions', 'DELETE'),
  ('public.role_permissions', 'INSERT'), ('public.role_permissions', 'UPDATE'), ('public.role_permissions', 'DELETE'),
  ('public.audit_logs', 'INSERT'), ('public.audit_logs', 'UPDATE'), ('public.audit_logs', 'DELETE'),
  ('public.financial_transactions', 'INSERT'), ('public.financial_transactions', 'UPDATE'), ('public.financial_transactions', 'DELETE'),
  ('public.communication_threads', 'INSERT'), ('public.communication_threads', 'UPDATE'), ('public.communication_threads', 'DELETE')
) denied(relation, privilege);

SELECT ok(has_function_privilege('anon', 'public.invitation_preview(text)', 'EXECUTE'),
  'anon still executes invitation_preview');
SELECT ok(has_function_privilege('authenticated', signature, 'EXECUTE'),
  'authenticated still executes ' || signature)
FROM unnest(ARRAY[
  'public.create_invitation(uuid,text,public.app_role)',
  'public.cancel_invitation(uuid)',
  'public.change_member_role(uuid,public.app_role)',
  'public.set_member_active(uuid,boolean)',
  'public.record_audit_event(uuid,text,text,uuid,jsonb)',
  'public.record_process_movement(uuid,uuid,text,public.process_stage,public.process_stage)'
]) signature;

SELECT ok(NOT has_function_privilege(client_role, p.oid, 'EXECUTE'),
  client_role || ' cannot execute internal function public.' || p.proname)
FROM pg_proc p
JOIN pg_namespace n ON n.oid = p.pronamespace
CROSS JOIN unnest(ARRAY['anon', 'authenticated']) client_role
WHERE n.nspname = 'public' AND p.proname IN (
  'financial_assert_editor', 'support_assert_admin', 'monitoring_assert_admin',
  'documents_authorization_guard', 'tasks_enforce_links', 'handle_new_user', 'set_updated_at'
);

SELECT ok(has_table_privilege('service_role', c.oid, 'SELECT'),
  'service_role retains SELECT on public.' || c.relname)
FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE n.nspname = 'public' AND c.relkind IN ('r', 'p');

CREATE TABLE public.stage18_default_table_probe(id bigint GENERATED BY DEFAULT AS IDENTITY);
CREATE FUNCTION public.stage18_default_function_probe() RETURNS void LANGUAGE sql AS 'SELECT';
SELECT ok(NOT has_table_privilege(client_role, 'public.stage18_default_table_probe', privilege),
  'new table does not default ' || privilege || ' to ' || client_role)
FROM unnest(ARRAY['PUBLIC', 'anon', 'authenticated']) client_role
CROSS JOIN unnest(ARRAY['SELECT', 'INSERT', 'UPDATE', 'DELETE', 'TRUNCATE', 'TRIGGER', 'REFERENCES']) privilege;
SELECT ok(NOT has_sequence_privilege(client_role, 'public.stage18_default_table_probe_id_seq', privilege),
  'new sequence does not default ' || privilege || ' to ' || client_role)
FROM unnest(ARRAY['PUBLIC', 'anon', 'authenticated']) client_role
CROSS JOIN unnest(ARRAY['USAGE', 'SELECT', 'UPDATE']) privilege;
SELECT ok(NOT has_function_privilege(client_role, 'public.stage18_default_function_probe()', 'EXECUTE'),
  'new function does not default EXECUTE to ' || client_role)
FROM unnest(ARRAY['PUBLIC', 'anon', 'authenticated']) client_role;

SELECT * FROM finish();
ROLLBACK;
