import assert from "node:assert/strict";
import { describe, test } from "node:test";
import { readFileSync } from "node:fs";
const migration=readFileSync("supabase/migrations/20260802230000_complete_team_permissions.sql","utf8");
const base=readFileSync("supabase/migrations/20260731184003_213e2283-a433-444c-9de8-cdd162bacfa2.sql","utf8");
const edge=readFileSync("supabase/functions/send-team-invitation/index.ts","utf8");
const page=readFileSync("src/routes/_authenticated/equipe.tsx","utf8");
const hook=readFileSync("src/hooks/use-team.ts","utf8");
const mutations=readFileSync("src/hooks/use-mutations.ts","utf8");
const invite=readFileSync("src/routes/convite.$token.tsx","utf8");
const all=page+invite+edge+hook;
describe("equipe e permissões",()=>{
 test("lista membros da organização",()=>assert.match(page,/useTeamMembers\(organizationId\)/));
 test("isola outra organização",()=>assert.match(migration,/is_org_member\(organization_id\)/));
 test("proprietário convida",()=>assert.match(migration,/proprietario','administrador/));
 test("administrador convida",()=>assert.match(migration,/role IN \('proprietario','administrador'\)/));
 for(const role of ["gestor","operacional","visualizador"]) test(`convite bloqueado para ${role}`,()=>assert.doesNotMatch(migration,new RegExp(`role IN \\([^)]*${role}`)));
 test("convite duplicado é reutilizado",()=>assert.match(migration,/ON CONFLICT \(organization_id,lower\(email\)\)/));
 test("convite expirado",()=>assert.match(base,/INVITE_EXPIRED/));
 test("convite cancelado",()=>assert.match(base,/INVITE_CANCELLED/));
 test("aceite com e-mail correto",()=>assert.match(base,/INVITE_EMAIL_MISMATCH/));
 test("rejeita e-mail diferente",()=>assert.match(base,/lower\(v_user.email\) <> lower\(v_inv.email\)/));
 test("aceite não cria organização",()=>assert.doesNotMatch(base.slice(base.indexOf('CREATE OR REPLACE FUNCTION public.accept_invitation'),base.indexOf('CREATE OR REPLACE FUNCTION public.change_member_role')),/INSERT INTO public.organizations/));
 test("impede membership duplicado",()=>assert.match(base,/ON CONFLICT ON CONSTRAINT organization_members_organization_id_user_id_key/));
 test("altera função por RPC",()=>assert.match(base,/change_member_role/));
 test("mutação de papel usa somente a RPC segura e não duplica auditoria",()=>{const fn=mutations.slice(mutations.indexOf("export function useUpdateMemberRole"),mutations.indexOf("/* ------------------------------------------------------------------ *",mutations.indexOf("export function useUpdateMemberRole")));assert.match(fn,/rpc\("change_member_role", \{ _member: memberId, _role: role \}\)/);assert.doesNotMatch(fn,/recordAudit\(/);assert.doesNotMatch(fn,/from\("organization_members"\).*update\(/s);});
 test("administrador não altera proprietário",()=>assert.match(base,/v_m.role = 'proprietario' OR _role IN \('proprietario','administrador'\)/));
 test("não altera própria função",()=>assert.match(base,/CANNOT_CHANGE_OWN_ROLE/));
 test("mantém proprietário ativo",()=>assert.match(base,/LAST_OWNER/));
 test("desativa membro sem excluir auth",()=>assert.match(base,/set_member_active/));
 test("desativa com transferência",()=>assert.match(base,/transfer_member_responsibilities/));
 test("reativa membro",()=>assert.match(base,/member.reactivated/));
 test("transfere tarefas",()=>assert.match(base,/UPDATE public.tasks SET assignee_id/));
 test("transfere processos",()=>assert.match(base,/UPDATE public.processes SET owner_id/));
 test("transfere monitoramentos",()=>assert.match(base,/UPDATE public.monitoring_items SET responsible_user_id/));
 test("visualizador somente leitura",()=>assert.match(migration,/RESTRICTIVE FOR UPDATE/));
 test("registra auditoria",()=>assert.match(migration,/INSERT INTO public.audit_logs/));
 test("isolamento é aplicado na consulta",()=>assert.match(page,/organizationId/));
 test("token puro não é persistido",()=>assert.match(migration,/token_hash/));
 test("convite reutilizado é bloqueado",()=>assert.match(base,/INVITE_ALREADY_ACCEPTED/));
 test("frontend não contém service role",()=>assert.doesNotMatch(all,/service_role/i));
 test("convite usa RPC segura diretamente",()=>assert.match(hook,/rpc\("create_invitation"/));
 test("convite não depende de Edge Function",()=>assert.doesNotMatch(hook,/functions\.invoke\("send-team-invitation"/));
 test("link usa a origem atual da aplicação",()=>assert.match(hook,/window\.location\.origin/));
});

describe("revisão de segurança do PR #3",()=>{
 test("origin malicioso do body é ignorado",()=>{assert.doesNotMatch(edge,/organizationId, email, role, origin/);assert.match(edge,/Deno\.env\.get\("APP_URL"\)/);});
 test("APP_URL ausente falha de forma segura",()=>assert.match(edge,/INVITATION_URL_NOT_CONFIGURED/));
 test("aceite bloqueia convite expirado",()=>assert.match(migration,/INVITE_EXPIRED/));
 test("aceite bloqueia convite cancelado",()=>assert.match(migration,/INVITE_CANCELLED/));
 test("aceite bloqueia convite reutilizado com lock",()=>assert.match(migration,/FOR UPDATE[\s\S]+INVITE_ALREADY_USED/));
 test("aceite rejeita e-mail autenticado diferente",()=>assert.match(migration,/INVITE_EMAIL_MISMATCH/));
 test("aceite rejeita membership ativa duplicada",()=>assert.match(migration,/MEMBERSHIP_ALREADY_EXISTS/));
 test("aceite não cria nova organização",()=>assert.doesNotMatch(migration,/INSERT INTO public\.organizations/));
 test("administrador não promove proprietário",()=>assert.match(migration,/v_m\.role='proprietario' OR _role IN \('proprietario','administrador'\)/));
 test("último proprietário não pode ser removido",()=>assert.match(migration,/RAISE EXCEPTION 'LAST_OWNER'/));
 test("transferência é uma função transacional",()=>assert.match(migration,/FUNCTION public\.transfer_member_responsibilities[\s\S]+UPDATE public\.tasks[\s\S]+UPDATE public\.processes[\s\S]+UPDATE public\.monitoring_items/));
 test("falha de transferência não desativa membro",()=>{const fn=migration.slice(migration.lastIndexOf("FUNCTION public.transfer_member_responsibilities"));assert.doesNotMatch(fn,/SET is_active=false/);});
 test("DELETE físico de tasks continua revogado",()=>assert.match(migration,/DROP POLICY IF EXISTS tasks_viewer_delete[\s\S]+REVOKE DELETE ON public\.tasks FROM authenticated/));
 test("preview nunca retorna token_hash",()=>{const fn=migration.slice(migration.indexOf("FUNCTION public.invitation_preview"),migration.indexOf("FUNCTION public.accept_invitation"));assert.doesNotMatch(fn,/RETURNS TABLE\([^)]*token_hash/);});
 test("CORS rejeita domínio não permitido",()=>{assert.match(edge,/ORIGIN_NOT_ALLOWED/);assert.doesNotMatch(edge,/Access-Control-Allow-Origin[^\n]+\*/);});
});
