/* global Deno */
import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "npm:@supabase/supabase-js@2.111.0";
const json=(value:unknown,status=200)=>new Response(JSON.stringify(value),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store"}});
const record=(value:unknown):Record<string,unknown>=>value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};
const text=(value:unknown)=>typeof value==="string"&&value.trim()?value.trim():null,encoder=new TextEncoder();
async function sha256(value:string){const digest=await crypto.subtle.digest("SHA-256",encoder.encode(value));return[...new Uint8Array(digest)].map((byte)=>byte.toString(16).padStart(2,"0")).join("");}
function safeEqual(left:string,right:string){if(left.length!==right.length)return false;let difference=0;for(let index=0;index<left.length;index+=1)difference|=left.charCodeAt(index)^right.charCodeAt(index);return difference===0;}
const acceptedEvents=new Set(["PAYMENT_CONFIRMED","PAYMENT_RECEIVED","PAYMENT_OVERDUE","PAYMENT_REFUNDED","PAYMENT_CHARGEBACK_REQUESTED","PAYMENT_CHARGEBACK_DISPUTE","PAYMENT_DELETED"]);
export default{async fetch(request:Request):Promise<Response>{if(request.method!=="POST")return json({error:"METHOD_NOT_ALLOWED"},405);const connectionToken=new URL(request.url).searchParams.get("connection");if(!connectionToken)return json({error:"CONNECTION_REQUIRED"},400);const supabaseUrl=Deno.env.get("SUPABASE_URL")??"",serviceKey=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")??"";if(!supabaseUrl||!serviceKey)return json({error:"SERVER_NOT_CONFIGURED"},503);const service=createClient(supabaseUrl,serviceKey,{auth:{persistSession:false,autoRefreshToken:false}});const{data:connection}=await service.from("asaas_connections").select("organization_id,webhook_token_hash,status").eq("public_token",connectionToken).eq("status","connected").maybeSingle();const suppliedToken=request.headers.get("asaas-access-token")??"";if(!connection?.webhook_token_hash||!suppliedToken||!safeEqual(await sha256(suppliedToken),connection.webhook_token_hash))return json({error:"INVALID_WEBHOOK_TOKEN"},401);let payload:Record<string,unknown>;try{payload=record(await request.json());}catch{return json({error:"INVALID_JSON"},400);}const eventId=text(payload.id),eventType=text(payload.event)?.toUpperCase(),payment=record(payload.payment),paymentId=text(payment.id);if(!eventId||!eventType||!paymentId)return json({error:"INVALID_EVENT"},400);if(!acceptedEvents.has(eventType))return json({received:true,ignored:eventType});const paidAtValue=text(payment.paymentDate)??text(payment.confirmedDate),paidAt=paidAtValue?new Date(`${paidAtValue}T12:00:00Z`).toISOString():null,amount=Number(payment.value);const{data,error}=await service.rpc("apply_asaas_payment_event",{_connection_token:connectionToken,_event_id:eventId,_event_type:eventType,_provider_payment_id:paymentId,_provider_status:text(payment.status)??"",_paid_at:paidAt,_amount:Number.isFinite(amount)&&amount>0?amount:null});if(error){console.error(JSON.stringify({source:"asaas-webhook",code:error.message.split(" ")[0],eventType}));return json({error:"WEBHOOK_PROCESSING_FAILED"},500);}return json({received:true,result:data});}};
