import { useMemo, useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { AlertCircle, Archive, CalendarClock, CheckCircle2, Clock3, Mail, MessageSquare, MessagesSquare, Phone, Plus, Search, StickyNote, UserRound } from "lucide-react";
import { toast } from "sonner";
import { useWorkspace } from "@/lib/workspace";
import { usePermissions } from "@/lib/permissions";
import { useClients, useProcesses } from "@/hooks/use-operations";
import { useTaskList } from "@/hooks/use-tasks";
import { useTeamMembers } from "@/hooks/use-team";
import { useAddCommunicationEntry, useAssignCommunicationThread, useChangeCommunicationStatus, useCommunicationEntries, useCommunicationSearchIndex, useCommunicationThreads, useCreateCommunicationThread, useUpdateCommunicationThread, type CommunicationThread, type NewCommunicationThread } from "@/hooks/use-communication";
import { COMMUNICATION_CHANNELS, COMMUNICATION_ENTRY_TYPES, COMMUNICATION_PRIORITIES, COMMUNICATION_STATUSES, canAdminCommunication, canWriteCommunication, communicationIndicators, filterCommunication, followUpState, type CommunicationChannel, type CommunicationEntryType, type CommunicationPriority, type CommunicationStatus } from "@/lib/communication";
import { describeError } from "@/lib/errors";
import { formatDate } from "@/lib/format";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";

export const Route = createFileRoute("/_authenticated/comunicacao")({ head: () => ({ meta: [{ title: "Comunicação — FLUXA" }, { name: "description", content: "Central interna de relacionamento e acompanhamento de contatos." }] }), component: CommunicationPage });
const labels = { aberta: "Aberta", aguardando_cliente: "Aguardando cliente", aguardando_equipe: "Aguardando equipe", resolvida: "Resolvida", arquivada: "Arquivada", baixa: "Baixa", normal: "Normal", alta: "Alta", urgente: "Urgente", whatsapp: "WhatsApp", telefone: "Telefone", email: "E-mail", presencial: "Presencial", interno: "Interno", outro: "Outro", mensagem: "Mensagem", nota_interna: "Nota interna", ligacao: "Ligação", reuniao: "Reunião", status: "Status", lembrete: "Lembrete", anexo: "Anexo" } as Record<string,string>;
const blank: NewCommunicationThread = { clientId: "", subject: "", channel: "interno", assignedTo: "", priority: "normal", processId: "", taskId: "", firstContent: "", followUpAt: "" };

function CommunicationPage() {
 const { organizationId, role } = useWorkspace(); const permissions = usePermissions();
 const query = useCommunicationThreads(organizationId); const searchIndex = useCommunicationSearchIndex(organizationId); const clients = useClients(organizationId); const processes = useProcesses(organizationId); const tasks = useTaskList(organizationId); const team = useTeamMembers(organizationId);
 const create = useCreateCommunicationThread(organizationId); const [selectedId,setSelectedId]=useState<string|null>(null); const [creating,setCreating]=useState(false); const [form,setForm]=useState(blank);
 const [search,setSearch]=useState(""); const [status,setStatus]=useState<CommunicationStatus|"all">("all"); const [priority,setPriority]=useState<CommunicationPriority|"all">("all"); const [channel,setChannel]=useState<CommunicationChannel|"all">("all"); const [client,setClient]=useState("all"); const [assignee,setAssignee]=useState("all"); const [followUp,setFollowUp]=useState<"all"|"today"|"overdue"|"future">("all");
 const memberNames = useMemo(()=>new Map((team.data??[]).map(m=>[m.user_id,m.full_name||m.email||"Sem nome"])),[team.data]);
 const summaries = (query.data??[]).map(row=>({...row,client_name:row.clients?.name??"Cliente",assigned_name:row.assigned_to?memberNames.get(row.assigned_to)??"Responsável":"Sem responsável",searchable_content:searchIndex.data?.get(row.id)??""}));
 const rows=filterCommunication(summaries,{search,status,priority,channel,client,assignee,followUp}); const indicators=communicationIndicators(summaries); const selected=(query.data??[]).find(r=>r.id===selectedId)??null;
 const submit=async(e:React.FormEvent)=>{e.preventDefault(); if(!form.clientId||form.subject.trim().length<3)return toast.error("Selecione o cliente e informe um assunto."); try{const id=await create.mutateAsync({...form,assignedTo:canAdminCommunication(role)?form.assignedTo:null,subject:form.subject.trim()});setCreating(false);setForm(blank);setSelectedId(id);toast.success("Conversa criada.");}catch(error){toast.error(describeError(error));}};
 return <div className="mx-auto w-full max-w-[1500px] space-y-5 p-4 sm:p-6">
  <header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="page-title">Comunicação</h1><p className="page-subtitle">Relacionamento, histórico de contatos e retornos da organização.</p></div>{canWriteCommunication(role)&&<Button onClick={()=>setCreating(true)}><Plus className="mr-2 size-4"/>Nova conversa</Button>}</header>
  <section className="grid grid-cols-2 gap-3 lg:grid-cols-5">{([{label:"Abertas",value:indicators.open,Icon:MessagesSquare},{label:"Aguardando cliente",value:indicators.waitingClient,Icon:Clock3},{label:"Aguardando equipe",value:indicators.waitingTeam,Icon:UserRound},{label:"Retornos atrasados",value:indicators.overdue,Icon:AlertCircle},{label:"Resolvidas",value:indicators.resolved,Icon:CheckCircle2}]).map(({label,value,Icon})=><Card key={String(label)}><CardContent className="p-4"><div className="flex items-center justify-between gap-2"><p className="field-label">{String(label)}</p><Icon className="size-4 text-muted-foreground"/></div><p className="metric-value mt-2">{String(value)}</p></CardContent></Card>)}</section>
  <Card><CardContent className="flex flex-wrap gap-2 p-3"><div className="relative min-w-56 flex-1"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input className="pl-9" placeholder="Cliente, assunto ou interação" value={search} onChange={e=>setSearch(e.target.value)}/></div><Filter value={status} set={setStatus} all="Todos os status" options={COMMUNICATION_STATUSES}/><Filter value={priority} set={setPriority} all="Prioridades" options={COMMUNICATION_PRIORITIES}/><Filter value={channel} set={setChannel} all="Canais" options={COMMUNICATION_CHANNELS}/><Filter value={client} set={setClient} all="Clientes" options={[...new Set(summaries.map(r=>r.client_name))]}/><Filter value={assignee} set={setAssignee} all="Responsáveis" options={[...new Set(summaries.map(r=>r.assigned_name??"Sem responsável"))]}/><Filter value={followUp} set={setFollowUp} all="Todos os retornos" options={["today","overdue","future"]} custom={{today:"Hoje",overdue:"Atrasados",future:"Futuros"}}/></CardContent></Card>
  <div className="grid min-h-[520px] gap-4 lg:grid-cols-[minmax(320px,0.85fr)_minmax(0,1.5fr)]"><Card className="overflow-hidden"><CardContent className="max-h-[680px] space-y-1 overflow-y-auto p-2">{query.isLoading?<p className="p-6 text-sm text-muted-foreground">Carregando conversas…</p>:rows.length===0?<Empty title="Nenhuma conversa encontrada" text={permissions.readOnly?"Não há conversas para os filtros escolhidos.":"Crie uma conversa para registrar o primeiro contato."}/>:rows.map(row=><ThreadItem key={row.id} row={row} active={row.id===selectedId} onClick={()=>setSelectedId(row.id)}/>)}</CardContent></Card>
   <Card className="min-w-0"><CardContent className="p-4 sm:p-5">{selected?<ThreadDetail thread={selected} memberNames={memberNames}/>:<Empty title="Selecione uma conversa" text="O histórico completo, os vínculos e as ações aparecerão aqui."/>}</CardContent></Card></div>
  <Dialog open={creating} onOpenChange={setCreating}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>Nova conversa</DialogTitle></DialogHeader><form className="grid gap-4 sm:grid-cols-2" onSubmit={submit}><Field label="Cliente *"><Select value={form.clientId} onValueChange={v=>setForm({...form,clientId:v,processId:"",taskId:""})}><SelectTrigger><SelectValue placeholder="Selecione"/></SelectTrigger><SelectContent>{(clients.data??[]).filter(c=>!c.archived_at).map(c=><SelectItem key={c.id} value={c.id}>{c.name}</SelectItem>)}</SelectContent></Select></Field><Field label="Assunto *"><Input value={form.subject} maxLength={240} onChange={e=>setForm({...form,subject:e.target.value})}/></Field><Field label="Canal"><EnumSelect value={form.channel} options={COMMUNICATION_CHANNELS} set={v=>setForm({...form,channel:v as CommunicationChannel})}/></Field><Field label="Prioridade"><EnumSelect value={form.priority} options={COMMUNICATION_PRIORITIES} set={v=>setForm({...form,priority:v as CommunicationPriority})}/></Field>{canAdminCommunication(role)&&<Field label="Responsável"><Select value={form.assignedTo||"none"} onValueChange={v=>setForm({...form,assignedTo:v==="none"?"":v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">Sem responsável</SelectItem>{(team.data??[]).filter(m=>m.is_active).map(m=><SelectItem key={m.user_id} value={m.user_id}>{m.full_name||m.email}</SelectItem>)}</SelectContent></Select></Field>}<Field label="Retornar em"><Input type="datetime-local" value={form.followUpAt??""} onChange={e=>setForm({...form,followUpAt:e.target.value})}/></Field><Field label="Processo"><Select value={form.processId||"none"} onValueChange={v=>setForm({...form,processId:v==="none"?"":v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">Sem vínculo</SelectItem>{(processes.data??[]).filter(p=>p.client_id===form.clientId).map(p=><SelectItem key={p.id} value={p.id}>{p.code} — {p.title}</SelectItem>)}</SelectContent></Select></Field><Field label="Tarefa"><Select value={form.taskId||"none"} onValueChange={v=>setForm({...form,taskId:v==="none"?"":v})}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">Sem vínculo</SelectItem>{(tasks.data??[]).filter(t=>!form.clientId||!t.client_id||t.client_id===form.clientId).map(t=><SelectItem key={t.id} value={t.id}>{t.title}</SelectItem>)}</SelectContent></Select></Field><div className="sm:col-span-2"><Field label="Primeira mensagem ou observação"><Textarea rows={4} value={form.firstContent??""} onChange={e=>setForm({...form,firstContent:e.target.value})}/></Field></div><div className="flex justify-end gap-2 sm:col-span-2"><Button type="button" variant="outline" onClick={()=>setCreating(false)}>Cancelar</Button><Button disabled={create.isPending}>Criar conversa</Button></div></form></DialogContent></Dialog>
 </div>;
}
function Filter({value,set,all,options,custom={}}:{value:string;set:(v:any)=>void;all:string;options:readonly string[];custom?:Record<string,string>}){return <Select value={value} onValueChange={set}><SelectTrigger className="w-40"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">{all}</SelectItem>{options.map(v=><SelectItem key={v} value={v}>{custom[v]??labels[v]??v}</SelectItem>)}</SelectContent></Select>}
function EnumSelect({value,options,set}:{value:string;options:readonly string[];set:(v:string)=>void}){return <Select value={value} onValueChange={set}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{options.map(v=><SelectItem key={v} value={v}>{labels[v]??v}</SelectItem>)}</SelectContent></Select>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="space-y-1.5"><Label>{label}</Label>{children}</div>}
function Empty({title,text}:{title:string;text:string}){return <div className="flex min-h-48 flex-col items-center justify-center p-6 text-center"><MessagesSquare className="mb-3 size-9 text-muted-foreground"/><h2 className="font-semibold">{title}</h2><p className="mt-1 max-w-sm text-sm text-muted-foreground">{text}</p></div>}
function ThreadItem({row,active,onClick}:{row:CommunicationThread&{client_name:string;assigned_name?:string|null};active:boolean;onClick:()=>void}){const follow=followUpState(row.follow_up_at);return <button type="button" onClick={onClick} className={`w-full rounded-lg border p-3 text-left transition-colors ${active?"border-primary bg-primary/5":"hover:bg-muted/60"}`}><div className="flex items-start justify-between gap-2"><div className="min-w-0"><p className="truncate font-semibold">{row.client_name}</p><p className="truncate text-sm">{row.subject}</p></div>{follow!=="none"&&<Badge variant={follow==="overdue"?"destructive":"secondary"}><CalendarClock className="mr-1 size-3"/>{follow==="today"?"Hoje":follow==="overdue"?"Atrasado":"Futuro"}</Badge>}</div><div className="mt-3 flex flex-wrap items-center gap-1.5"><Badge variant="outline">{labels[row.status]}</Badge><Badge variant={row.priority==="urgente"?"destructive":"secondary"}>{labels[row.priority]}</Badge><span className="ml-auto text-xs text-muted-foreground">{formatDate(row.updated_at)}</span></div></button>}
function ThreadDetail({thread,memberNames}:{thread:CommunicationThread;memberNames:Map<string,string>}){
 const {organizationId,role}=useWorkspace(); const entries=useCommunicationEntries(thread.id); const add=useAddCommunicationEntry(organizationId); const change=useChangeCommunicationStatus(organizationId); const assign=useAssignCommunicationThread(organizationId); const update=useUpdateCommunicationThread(organizationId); const team=useTeamMembers(organizationId);
 const [type,setType]=useState<CommunicationEntryType>("mensagem"); const [content,setContent]=useState(""); const [occurred,setOccurred]=useState(""); const [internal,setInternal]=useState(false); const [contact,setContact]=useState(false); const [follow,setFollow]=useState(""); const write=canWriteCommunication(role); const admin=canAdminCommunication(role);
 const addEntry=async(e:React.FormEvent)=>{e.preventDefault();if(!content.trim())return;try{await add.mutateAsync({threadId:thread.id,type,content:content.trim(),occurredAt:occurred?new Date(occurred).toISOString():undefined,internal:internal||type==="nota_interna",contactMade:contact});setContent("");setInternal(false);setContact(false);toast.success("Interação registrada.");}catch(error){toast.error(describeError(error));}};
 const setStatus=async(status:CommunicationStatus)=>{try{await change.mutateAsync({threadId:thread.id,status});toast.success("Status atualizado.");}catch(error){toast.error(describeError(error));}};
 const saveFollow=async()=>{try{await update.mutateAsync({threadId:thread.id,followUpAt:follow?new Date(follow).toISOString():null,clearFollowUp:!follow});toast.success(follow?"Retorno agendado.":"Lembrete removido.");}catch(error){toast.error(describeError(error));}};
 return <div className="space-y-5"><header className="border-b pb-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm text-muted-foreground">{thread.clients?.name}</p><h2 className="text-xl font-semibold">{thread.subject}</h2></div><div className="flex flex-wrap gap-2"><Badge>{labels[thread.status]}</Badge><Badge variant={thread.priority==="urgente"?"destructive":"secondary"}>{labels[thread.priority]}</Badge><Badge variant="outline">{labels[thread.channel]}</Badge></div></div><div className="mt-3 grid gap-2 text-sm sm:grid-cols-2 xl:grid-cols-3"><span>Criada em {formatDate(thread.created_at)}</span><span>Responsável: {thread.assigned_to?memberNames.get(thread.assigned_to)??"Membro":"Não atribuído"}</span><span>{thread.follow_up_at?`Retorno: ${formatDate(thread.follow_up_at)}`:"Sem retorno agendado"}</span>{thread.clients&&<Link className="text-primary hover:underline" to="/clientes/$clientId" params={{clientId:thread.clients.id}}>Abrir cliente</Link>}{thread.processes&&<Link className="text-primary hover:underline" to="/processos/$processId" params={{processId:thread.processes.id}}>Processo {thread.processes.code}</Link>}{thread.tasks&&<Link className="text-primary hover:underline" to="/tarefas">Tarefa: {thread.tasks.title}</Link>}</div></header>
 {write&&<div className="flex flex-wrap gap-2"><Select value={thread.status} onValueChange={v=>setStatus(v as CommunicationStatus)}><SelectTrigger className="w-48"><SelectValue/></SelectTrigger><SelectContent>{COMMUNICATION_STATUSES.filter(v=>v!=="arquivada"||admin).map(v=><SelectItem key={v} value={v}>{labels[v]}</SelectItem>)}</SelectContent></Select>{admin&&<Select value={thread.assigned_to??"none"} onValueChange={async v=>{try{await assign.mutateAsync({threadId:thread.id,assignedTo:v==="none"?null:v});toast.success("Responsável atualizado.");}catch(error){toast.error(describeError(error));}}}><SelectTrigger className="w-52"><SelectValue placeholder="Responsável"/></SelectTrigger><SelectContent><SelectItem value="none">Sem responsável</SelectItem>{(team.data??[]).filter(m=>m.is_active).map(m=><SelectItem key={m.user_id} value={m.user_id}>{m.full_name||m.email}</SelectItem>)}</SelectContent></Select>}<Input className="w-52" type="datetime-local" value={follow} onChange={e=>setFollow(e.target.value)}/><Button variant="outline" onClick={saveFollow}><CalendarClock className="mr-2 size-4"/>Retornar em</Button>{admin&&thread.status!=="arquivada"&&<Button variant="outline" onClick={()=>setStatus("arquivada")}><Archive className="mr-2 size-4"/>Arquivar</Button>}</div>}
 <section><h3 className="mb-3 font-semibold">Timeline</h3><div className="max-h-[390px] space-y-3 overflow-y-auto pr-1">{entries.isLoading?<p className="text-sm text-muted-foreground">Carregando histórico…</p>:(entries.data??[]).length===0?<p className="rounded-lg border border-dashed p-6 text-center text-sm text-muted-foreground">Nenhuma interação registrada.</p>:(entries.data??[]).map(entry=>{const note=entry.is_internal||entry.entry_type==="nota_interna";const Icon=entry.entry_type==="ligacao"?Phone:entry.entry_type==="email"?Mail:note?StickyNote:MessageSquare;return <article key={entry.id} className={`rounded-lg border p-3 ${note?"border-amber-300 bg-amber-50/70 dark:bg-amber-950/20":"bg-card"}`}><div className="flex flex-wrap items-center gap-2 text-xs text-muted-foreground"><Icon className="size-4"/><strong className="text-foreground">{labels[entry.entry_type]??entry.entry_type}</strong>{note&&<Badge variant="outline">Somente equipe</Badge>}{entry.contact_made&&<Badge variant="secondary">Contato realizado</Badge>}<time className="ml-auto">{formatDate(entry.occurred_at)}</time></div><p className="mt-2 whitespace-pre-wrap text-sm">{entry.content}</p></article>})}</div></section>
 {write&&thread.status!=="arquivada"&&<form onSubmit={addEntry} className="space-y-3 rounded-lg border bg-muted/20 p-3"><div className="flex flex-wrap gap-2"><Select value={type} onValueChange={v=>{setType(v as CommunicationEntryType);if(v==="nota_interna")setInternal(true)}}><SelectTrigger className="w-44"><SelectValue/></SelectTrigger><SelectContent>{COMMUNICATION_ENTRY_TYPES.filter(v=>!["status","lembrete","anexo"].includes(v)).map(v=><SelectItem key={v} value={v}>{labels[v]}</SelectItem>)}</SelectContent></Select><Input className="w-52" type="datetime-local" value={occurred} onChange={e=>setOccurred(e.target.value)}/></div><Textarea placeholder={type==="nota_interna"?"Nota visível somente para a equipe":"Conteúdo da interação"} value={content} onChange={e=>setContent(e.target.value)} rows={3}/><div className="flex flex-wrap items-center gap-4"><label className="flex items-center gap-2 text-sm"><Checkbox checked={internal||type==="nota_interna"} disabled={type==="nota_interna"} onCheckedChange={v=>setInternal(Boolean(v))}/>Visibilidade interna</label><label className="flex items-center gap-2 text-sm"><Checkbox checked={contact} onCheckedChange={v=>setContact(Boolean(v))}/>Contato realizado</label><Button className="ml-auto" disabled={add.isPending}>Registrar interação</Button></div></form>}
 </div>;
}
