import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { AlertTriangle, Download, Plus, Printer, RefreshCw, WalletCards } from "lucide-react";
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useFinance, useFinancialAction, useFinancialPayment } from "@/hooks/use-finance";
import { brDate, brl, downloadFinancialCsv, financialBuckets, financeViewState } from "@/lib/finance";
import { useWorkspace } from "@/lib/workspace";

export const Route = createFileRoute("/_authenticated/financeiro")({ head:()=>({meta:[{title:"Financeiro — FLUXA"},{name:"description",content:"Gestão financeira segura da organização."}]}), component:FinancePage });
const colors=["#2563eb","#16a34a","#dc2626","#d97706","#7c3aed"];
const statusLabel:Record<string,string>={pending:"Pendente",partial:"Parcial",paid:"Pago",overdue:"Atrasado",cancelled:"Cancelado"};
const selectClass="h-9 rounded-md border border-input bg-background px-3 text-sm";

function FinancePage(){
 const {organizationId,membership,role}=useWorkspace(); const query=useFinance(organizationId); const action=useFinancialAction(organizationId); const payment=useFinancialPayment(organizationId);
 const state=financeViewState(organizationId,query);
 if(state==="missing-organization")return <div className="p-6"><h1 className="page-title">Financeiro</h1><p>Selecione uma organização ativa.</p></div>;
 if(state==="loading")return <div className="mx-auto w-full max-w-7xl p-4 sm:p-6"><Card><CardContent className="p-8 text-center">Carregando dados financeiros reais…</CardContent></Card></div>;
 if(state==="error")return <div className="mx-auto w-full max-w-7xl p-4 sm:p-6"><Card><CardContent role="alert" className="p-6 text-destructive"><AlertTriangle className="inline"/> Não foi possível carregar. <Button onClick={()=>query.refetch()}>Tentar novamente</Button></CardContent></Card></div>;
 if(!query.data)return null;
 return <FinanceContent data={query.data} membership={membership} role={role} action={action} payment={payment}/>;
}

function FinanceContent({data,membership,role,action,payment}:any){
 const [tab,setTab]=useState("overview"),[search,setSearch]=useState(""),[status,setStatus]=useState("all"),[type,setType]=useState("all"),[category,setCategory]=useState("all"),[account,setAccount]=useState("all"),[from,setFrom]=useState(""),[to,setTo]=useState(""),[page,setPage]=useState(0);
 const transactions=data?.transactions??[],categories=data?.categories??[],accounts=data?.accounts??[],payments=data?.payments??[],recurrences=data?.recurrences??[];
 const editable=!["visualizador","operacional","atendimento","cliente_externo"].includes(role??""); const rows=useMemo(()=> transactions.filter((x:any)=>!x.archived_at&&(type==="all"||x.type===type)&&(status==="all"||x.status===status)&&(category==="all"||x.category_id===category)&&(account==="all"||x.account_id===account)&&(!from||x.due_date>=from)&&(!to||x.due_date<=to)&&JSON.stringify(x).toLowerCase().includes(search.toLowerCase())),[transactions,type,status,category,account,from,to,search]);
 const paid=(id:string)=>payments.filter((x:any)=>x.transaction_id===id&&!x.reversed_at).reduce((n:number,x:any)=>n+Number(x.amount),0); const now=new Date();
 const metrics=useMemo(()=>{const tx=transactions.filter((x:any)=>!x.archived_at&&x.status!=="cancelled"),month=now.toISOString().slice(0,7),open=tx.filter((x:any)=>x.status!=="paid"); const sum=(r:any[])=>r.reduce((n,x)=>n+Number(x.amount),0); return [["Saldo atual",sum(accounts.map((x:any)=>({amount:x.current_balance})))],["Total a receber",sum(open.filter((x:any)=>x.type==="income"))],["Total a pagar",sum(open.filter((x:any)=>x.type==="expense"))],["Receitas do mês",sum(tx.filter((x:any)=>x.type==="income"&&x.due_date.startsWith(month)))],["Despesas do mês",sum(tx.filter((x:any)=>x.type==="expense"&&x.due_date.startsWith(month)))],["Valores vencidos",sum(open.filter((x:any)=>financialBuckets(x.due_date,x.status,now).overdue))],["Vencendo em 7 dias",sum(open.filter((x:any)=>financialBuckets(x.due_date,x.status,now).in7))],["Vencendo em 30 dias",sum(open.filter((x:any)=>financialBuckets(x.due_date,x.status,now).in30))]] as [string,number][]},[transactions,accounts]);
 const monthIncome=metrics.find(x=>x[0]==="Receitas do mês")?.[1]??0,monthExpense=metrics.find(x=>x[0]==="Despesas do mês")?.[1]??0; const chart=monthly(transactions),expenseCategories=byCategory({transactions,categories},"expense"),incomeCategories=byCategory({transactions,categories},"income");
 const exportRows=()=>downloadFinancialCsv(tab,rows.map((x:any)=>({Descrição:x.description,Tipo:x.type==="income"?"Receita":"Despesa",Valor:brl(Number(x.amount)),Vencimento:brDate(x.due_date),Status:statusLabel[x.status],Pago:brl(paid(x.id)),Saldo:brl(Number(x.amount)-paid(x.id))})));
 return <div className="finance-page mx-auto w-full max-w-7xl space-y-5 p-4 sm:p-6"><header className="print-header flex flex-wrap justify-between gap-3"><div><h1 className="page-title">Financeiro</h1><p className="page-subtitle">Visão financeira real de {membership?.organizations?.trade_name||membership?.organizations?.legal_name}.</p><p className="hidden print:block">Gerado em {new Date().toLocaleString("pt-BR")} · Período {from?brDate(from):"início"} a {to?brDate(to):"hoje"}</p></div><div className="no-print flex flex-wrap gap-2"><Button variant="outline" onClick={()=>window.print()}><Printer/>Imprimir / PDF</Button><Button variant="outline" disabled={!rows.length} onClick={exportRows}><Download/>CSV</Button>{editable&&<TransactionDialog data={data} onSave={async (payload:Record<string,unknown>)=>{await action.mutateAsync({rpc:"create_financial_transaction",payload});toast.success("Lançamento criado.")}}/>}</div></header>
 <Tabs value={tab} onValueChange={setTab}><TabsList className="no-print h-auto flex-wrap">{[["overview","Visão geral"],["receivable","Contas a receber"],["payable","Contas a pagar"],["income","Receitas"],["expense","Despesas"],["cashflow","Fluxo de caixa"],["categories","Categorias"],["accounts","Contas"],["recurrences","Recorrências"]].map(([v,l])=><TabsTrigger key={v} value={v}>{l}</TabsTrigger>)}</TabsList>
 <TabsContent value="overview" className="space-y-4"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[...metrics,["Resultado do mês",monthIncome-monthExpense]].map(([l,v])=><Card key={String(l)}><CardHeader className="pb-2"><CardTitle className="text-sm text-muted-foreground">{l}</CardTitle></CardHeader><CardContent className="text-2xl font-semibold">{brl(Number(v))}</CardContent></Card>)}</div><div className="grid gap-4 lg:grid-cols-2"><Chart title="Receitas x despesas por mês" data={chart}/><Chart title="Fluxo de caixa mensal" data={chart.map(x=>({...x,fluxo:x.receitas-x.despesas}))} keys={["fluxo"]}/><PieBlock title="Despesas por categoria" data={expenseCategories}/><PieBlock title="Receitas por categoria" data={incomeCategories}/><PieBlock title="Contas a receber por status" data={byStatus(transactions,"income")}/><PieBlock title="Contas a pagar por status" data={byStatus(transactions,"expense")}/></div></TabsContent>
 {[["receivable","income"],["payable","expense"],["income","income"],["expense","expense"]].map(([v,t])=><TabsContent key={v} value={v}><Filters {...{search,setSearch,status,setStatus,type,setType,category,setCategory,account,setAccount,from,setFrom,to,setTo,data}}/><Transactions rows={rows.filter((x:any)=>x.type===t)} data={data} paid={paid} editable={editable} page={page} setPage={setPage} payment={payment}/></TabsContent>)}
 <TabsContent value="cashflow"><Chart title="Fluxo de caixa mensal" data={chart.map(x=>({...x,fluxo:x.receitas-x.despesas}))} keys={["fluxo"]}/></TabsContent><TabsContent value="categories"><SimpleList title="Categorias" rows={categories} empty="Nenhuma categoria cadastrada."/></TabsContent><TabsContent value="accounts"><SimpleList title="Contas e saldos" rows={accounts.map((x:any)=>({...x,name:`${x.name} · ${brl(Number(x.current_balance))}`}))} empty="Nenhuma conta cadastrada."/></TabsContent><TabsContent value="recurrences"><SimpleList title="Lançamentos recorrentes" rows={recurrences} empty="Nenhuma recorrência cadastrada." action={editable?<Button onClick={async()=>{await action.mutateAsync({rpc:"generate_recurrence_transactions",payload:{until:new Date().toISOString().slice(0,10)}});toast.success("Próximos lançamentos gerados.")}}><RefreshCw/>Gerar próximos lançamentos</Button>:undefined}/></TabsContent>
 </Tabs></div>
}

function Filters(p:any){return <Card className="no-print mb-4"><CardContent className="grid gap-3 pt-6 sm:grid-cols-2 lg:grid-cols-4"><Input aria-label="Buscar" placeholder="Buscar lançamento…" value={p.search} onChange={e=>p.setSearch(e.target.value)}/><Select label="Status" value={p.status} set={p.setStatus} options={Object.entries(statusLabel)}/><Select label="Categoria" value={p.category} set={p.setCategory} options={p.data.categories.map((x:any)=>[x.id,x.name])}/><Select label="Conta" value={p.account} set={p.setAccount} options={p.data.accounts.map((x:any)=>[x.id,x.name])}/><Label>De<Input type="date" value={p.from} onChange={e=>p.setFrom(e.target.value)}/></Label><Label>Até<Input type="date" value={p.to} onChange={e=>p.setTo(e.target.value)}/></Label></CardContent></Card>}
function Select({label,value,set,options}:any){return <Label>{label}<select className={`${selectClass} w-full`} value={value} onChange={e=>set(e.target.value)}><option value="all">Todos</option>{options.map((x:any)=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></Label>}
function Transactions({rows,data,paid,editable,page,setPage,payment}:any){const shown=rows.slice(page*10,page*10+10);return <Card><CardContent className="overflow-x-auto pt-6">{!shown.length?<p className="py-10 text-center text-muted-foreground">Nenhum lançamento encontrado.</p>:<table className="w-full text-sm"><thead><tr>{["Descrição","Tipo","Valor","Vencimento","Status","Categoria","Conta","Valor pago","Saldo restante","Ações"].map(x=><th className="p-2 text-left" key={x}>{x}</th>)}</tr></thead><tbody>{shown.map((x:any)=>{const total=paid(x.id);return <tr className="border-t" key={x.id}><td className="p-2 font-medium">{x.description}</td><td>{x.type==="income"?"Receita":"Despesa"}</td><td>{brl(x.amount)}</td><td>{brDate(x.due_date)}</td><td>{statusLabel[x.status]}</td><td>{data.categories.find((c:any)=>c.id===x.category_id)?.name??"—"}</td><td>{data.accounts.find((a:any)=>a.id===x.account_id)?.name??"—"}</td><td>{brl(total)}</td><td>{brl(x.amount-total)}</td><td>{editable&&!["paid","cancelled"].includes(x.status)&&<PayDialog transaction={x} accounts={data.accounts} payment={payment}/>}</td></tr>})}</tbody></table>}<div className="no-print mt-4 flex justify-between"><Button variant="outline" disabled={!page} onClick={()=>setPage(page-1)}>Anterior</Button><span>Página {page+1}</span><Button variant="outline" disabled={(page+1)*10>=rows.length} onClick={()=>setPage(page+1)}>Próxima</Button></div></CardContent></Card>}
function TransactionDialog({data,onSave}:any){const [open,setOpen]=useState(false),[form,setForm]=useState({description:"",type:"income",amount:"",due_date:new Date().toISOString().slice(0,10),category_id:"",account_id:""});return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button><Plus/>Novo lançamento</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Novo lançamento</DialogTitle></DialogHeader><div className="grid gap-3"><Label>Descrição<Input value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Label><Select label="Tipo" value={form.type} set={(v:string)=>setForm({...form,type:v})} options={[["income","Receita"],["expense","Despesa"]]}/><Label>Valor<Input type="number" min="0.01" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></Label><Label>Vencimento<Input type="date" value={form.due_date} onChange={e=>setForm({...form,due_date:e.target.value})}/></Label><Select label="Categoria" value={form.category_id||"all"} set={(v:string)=>setForm({...form,category_id:v==="all"?"":v})} options={data.categories.map((x:any)=>[x.id,x.name])}/><Select label="Conta" value={form.account_id||"all"} set={(v:string)=>setForm({...form,account_id:v==="all"?"":v})} options={data.accounts.map((x:any)=>[x.id,x.name])}/></div><DialogFooter><Button disabled={!form.description||Number(form.amount)<=0} onClick={async()=>{await onSave({...form,amount:Number(form.amount),category_id:form.category_id||null,account_id:form.account_id||null});setOpen(false)}}>Salvar</Button></DialogFooter></DialogContent></Dialog>}
function PayDialog({transaction,accounts,payment}:any){const [open,setOpen]=useState(false),[amount,setAmount]=useState(String(transaction.amount)),[accountId,setAccount]=useState(transaction.account_id||accounts[0]?.id||"");return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button size="sm" variant="outline"><WalletCards/>Pagar</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Registrar pagamento</DialogTitle></DialogHeader><Label>Valor<Input type="number" min="0.01" max={transaction.amount} step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></Label><Select label="Conta" value={accountId} set={setAccount} options={accounts.map((x:any)=>[x.id,x.name])}/><DialogFooter><Button disabled={!accountId||Number(amount)<=0} onClick={async()=>{await payment.mutateAsync({transactionId:transaction.id,amount:Number(amount),accountId});toast.success("Pagamento registrado.");setOpen(false)}}>Confirmar pagamento</Button></DialogFooter></DialogContent></Dialog>}
function Chart({title,data,keys=["receitas","despesas"]}:any){return <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent>{!data.length?<p className="flex h-56 items-center justify-center">Sem dados no período.</p>:<div className="h-64" role="img" aria-label={title}><ResponsiveContainer><BarChart data={data}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month"/><YAxis/><Tooltip formatter={(v:number)=>brl(v)}/>{keys.map((k:string,i:number)=><Bar key={k} dataKey={k} fill={colors[i]} radius={[4,4,0,0]}/>)}</BarChart></ResponsiveContainer></div>}</CardContent></Card>}
function PieBlock({title,data}:any){return <Card><CardHeader><CardTitle>{title}</CardTitle></CardHeader><CardContent>{!data.length?<p className="flex h-56 items-center justify-center">Sem dados no período.</p>:<div className="h-64" role="img" aria-label={title}><ResponsiveContainer><PieChart><Pie data={data} dataKey="value" nameKey="name" label>{data.map((_:any,i:number)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip formatter={(v:number)=>brl(v)}/></PieChart></ResponsiveContainer></div>}</CardContent></Card>}
function SimpleList({title,rows,empty,action}:any){return <Card><CardHeader className="flex-row justify-between"><CardTitle>{title}</CardTitle>{action}</CardHeader><CardContent>{!rows.length?<p>{empty}</p>:<ul className="divide-y">{rows.map((x:any)=><li className="flex justify-between py-3" key={x.id}><span>{x.name}</span><span>{x.is_active===false?"Inativo":x.status??"Ativo"}</span></li>)}</ul>}</CardContent></Card>}
function monthly(rows:any[]=[]){const m=new Map<string,{month:string;receitas:number;despesas:number}>();rows.filter(x=>!x.archived_at&&x.status!=="cancelled"&&x.due_date).forEach(x=>{const key=x.due_date.slice(0,7),v=m.get(key)??{month:key,receitas:0,despesas:0};v[x.type==="income"?"receitas":"despesas"]+=Number(x.amount);m.set(key,v)});return [...m.values()].sort((a,b)=>a.month.localeCompare(b.month)).slice(-12)}
function byCategory(data:any,type:string){const transactions=data?.transactions??[],categories=data?.categories??[],m=new Map<string,number>();transactions.filter((x:any)=>x.type===type&&!x.archived_at&&x.status!=="cancelled").forEach((x:any)=>{const n=categories.find((c:any)=>c.id===x.category_id)?.name??"Sem categoria";m.set(n,(m.get(n)??0)+Number(x.amount))});return [...m].map(([name,value])=>({name,value}))}
function byStatus(rows:any[]=[],type:string){const m=new Map<string,number>();rows.filter(x=>x.type===type&&!x.archived_at).forEach(x=>m.set(statusLabel[x.status],(m.get(statusLabel[x.status])??0)+Number(x.amount)));return [...m].map(([name,value])=>({name,value}))}
