import { useMemo, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { CheckCircle2, ExternalLink, Search } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Textarea } from "@/components/ui/textarea";
import { Skeleton } from "@/components/ui/skeleton";
import { useOperationalMonitoring, useMonitoringActions } from "@/hooks/use-monitoring-center";
import { useOrganizationSettings } from "@/hooks/use-organization-settings";
import { useTeamMembers } from "@/hooks/use-team";
import { useWorkspace } from "@/lib/workspace";
import { usePermissions } from "@/lib/permissions";
import { effectivePriority, filterMonitoringAlerts, sourcePath, type MonitoringAlert, type MonitoringPriority, type MonitoringStatus } from "@/lib/monitoring";
import { formatDate, formatDateTime, formatNumber } from "@/lib/format";
import { describeError } from "@/lib/errors";
import { formatUpcomingDaysLabel } from "@/lib/organization-settings";

export const Route = createFileRoute("/_authenticated/monitoramento")({
  head: () => ({ meta: [{ title: "Central de Monitoramento — FLUXA" }, { name: "description", content: "Alertas operacionais e acompanhamento humano da organização." }] }), component: Page,
});
const ALL = "todos";
const sourceLabel: Record<string,string> = { tarefa:"Tarefa", processo:"Processo", documento:"Documento", comunicacao:"Comunicação", financeiro:"Financeiro", outro:"Outro" };
const statusLabel: Record<string,string> = { novo:"Novo", em_analise:"Em análise", acompanhado:"Acompanhado", resolvido:"Resolvido", ignorado:"Ignorado" };
const priorityLabel: Record<string,string> = { baixa:"Baixo", media:"Médio", alta:"Alto", critica:"Crítico" };
const priorityTone: Record<string,string> = { baixa:"bg-muted text-muted-foreground", media:"bg-blue-100 text-blue-800", alta:"bg-amber-100 text-amber-800", critica:"bg-red-100 text-red-800" };
const monitoringAdmins = ["superadmin", "proprietario", "administrador", "gestor"];

function Page() {
  const { organizationId } = useWorkspace(); const permissions = usePermissions();
  const canAdminMonitoring = Boolean(permissions.role && monitoringAdmins.includes(permissions.role));
  const canFollowUp = canAdminMonitoring || permissions.role === "operacional";
  const query = useOperationalMonitoring(organizationId); const actions = useMonitoringActions(organizationId); const team = useTeamMembers(organizationId);
  const settings = useOrganizationSettings(organizationId);
  const [filter,setFilter] = useState({ search:"",type:ALL,status:ALL,priority:ALL,window:ALL,responsibleId:ALL,clientId:ALL }); const [selected,setSelected] = useState<MonitoringAlert|null>(null);
  const clients=useMemo(()=>[...new Map((query.data??[]).filter(x=>x.client_id&&x.client_name).map(x=>[x.client_id!,x.client_name!])).entries()], [query.data]);
  const rows = useMemo(()=>filterMonitoringAlerts(query.data??[],filter),[query.data,filter]);
  const all=query.data??[]; const totals={ critical:all.filter(x=>effectivePriority(x)==="critica"&&!["resolvido","ignorado"].includes(x.monitoring_status)).length, overdue:all.filter(x=>(x.days_delta??0)<0).length, today:all.filter(x=>x.days_delta===0).length, next7:all.filter(x=>x.days_delta!==null&&x.days_delta>0&&x.days_delta<=7).length, stale:all.filter(x=>x.alert_kind==="processo_sem_movimentacao").length, resolved:all.filter(x=>x.monitoring_status==="resolvido"&&x.state_updated_at&&Date.now()-new Date(x.state_updated_at).getTime()<=7*864e5).length };
  const set = (key:string,value:string)=>setFilter(f=>({...f,[key]:value}));
  const act=async(fn:()=>Promise<void>,message:string)=>{try{await fn();toast.success(message)}catch(e){toast.error(describeError(e,"monitoramento"))}};
  return <div className="mx-auto w-full max-w-7xl space-y-5 p-4 sm:p-6">
    <header><h1 className="page-title">Central de Monitoramento Operacional</h1><p className="page-subtitle mt-1">Situações derivadas dos registros da organização. O acompanhamento não altera a entidade original.</p></header>
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-6">{[
      ["Críticos",totals.critical,"priority","critica"],["Atrasados",totals.overdue,"window","vencidos"],["Vencem hoje",totals.today,"window","hoje"],[formatUpcomingDaysLabel(settings.data?.monitoring_upcoming_days),totals.next7,"window","7"],["Sem movimentação",totals.stale,"window","sem_movimentacao"],["Resolvidos recentemente",totals.resolved,"status","resolvido"]
    ].map(([label,value,key,val])=><button key={String(label)} onClick={()=>set(String(key),String(val))} className="rounded-lg text-left focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><Card className="h-full transition-colors hover:border-primary"><CardContent className="p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-2xl font-semibold">{formatNumber(Number(value))}</p></CardContent></Card></button>)}</div>
    <Card><CardContent className="grid gap-3 p-4 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7"><div className="relative sm:col-span-2"><Search className="absolute left-3 top-3 size-4 text-muted-foreground"/><Input className="pl-9" placeholder="Cliente, título, processo, descrição ou responsável" value={filter.search} onChange={e=>set("search",e.target.value)}/></div><Filter value={filter.type} set={v=>set("type",v)} label="Tipo" values={Object.entries(sourceLabel)}/><Filter value={filter.clientId} set={v=>set("clientId",v)} label="Cliente" values={clients}/><Filter value={filter.responsibleId} set={v=>set("responsibleId",v)} label="Responsável" values={(team.data??[]).map(m=>[m.user_id,m.full_name??m.email??"Membro"])}/><Filter value={filter.status} set={v=>set("status",v)} label="Status" values={Object.entries(statusLabel)}/><Filter value={filter.priority} set={v=>set("priority",v)} label="Prioridade" values={Object.entries(priorityLabel)}/><Filter value={filter.window} set={v=>set("window",v)} label="Período" values={[["vencidos","Vencidos"],["hoje","Hoje"],["7","Próximos 7 dias"],["30","Próximos 30 dias"],["sem_movimentacao","Sem movimentação"]]}/></CardContent></Card>
    {query.isLoading?<div className="space-y-3">{[1,2,3].map(x=><Skeleton key={x} className="h-24"/>)}</div>:query.isError?<Card><CardContent className="p-6 text-destructive">Não foi possível carregar os alertas. Tente novamente.</CardContent></Card>:rows.length===0?<Card><CardContent className="flex flex-col items-center p-12 text-center"><CheckCircle2 className="mb-3 size-10 text-emerald-600"/><h2 className="font-semibold">Tudo em dia</h2><p className="text-sm text-muted-foreground">Nenhum item exige atenção para os filtros selecionados.</p></CardContent></Card>:<div className="overflow-hidden rounded-lg border bg-card"><div className="hidden grid-cols-[2fr_1fr_1fr_1fr_auto] gap-3 border-b bg-muted/40 p-3 text-xs font-medium text-muted-foreground md:grid"><span>Alerta / origem</span><span>Responsável</span><span>Prazo</span><span>Acompanhamento</span><span>Ação</span></div>{rows.map(a=><button key={`${a.source_type}:${a.source_id}:${a.alert_kind}`} onClick={()=>setSelected(a)} className="grid w-full gap-2 border-b p-4 text-left last:border-0 hover:bg-muted/30 md:grid-cols-[2fr_1fr_1fr_1fr_auto] md:items-center"><div className="min-w-0"><div className="flex flex-wrap gap-2"><strong className="truncate text-sm">{a.title}</strong><Badge variant="outline">{sourceLabel[a.source_type]}</Badge><Badge className={priorityTone[effectivePriority(a)]}>{priorityLabel[effectivePriority(a)]}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{a.reason}{a.client_name?` · ${a.client_name}`:""}{a.process_code?` · ${a.process_code}`:""}</p></div><span className="text-sm">{a.assigned_name??a.responsible_name??"Não atribuído"}</span><span className="text-sm">{formatDate(a.relevant_at)}</span><Badge variant="secondary" className="w-fit">{statusLabel[a.monitoring_status]}</Badge><ExternalLink className="size-4 text-muted-foreground"/></button>)}</div>}
    <Sheet open={Boolean(selected)} onOpenChange={o=>!o&&setSelected(null)}><SheetContent className="w-full overflow-y-auto sm:max-w-xl">{selected&&<div className="space-y-5 p-1"><SheetHeader><SheetTitle>{selected.title}</SheetTitle><SheetDescription>{selected.reason}</SheetDescription></SheetHeader><div className="flex flex-wrap gap-2"><Badge>{sourceLabel[selected.source_type]}</Badge><Badge className={priorityTone[effectivePriority(selected)]}>{priorityLabel[effectivePriority(selected)]}</Badge><Badge variant="secondary">{statusLabel[selected.monitoring_status]}</Badge></div><dl className="grid grid-cols-2 gap-3 text-sm"><Info l="Cliente" v={selected.client_name}/><Info l="Processo" v={selected.process_code}/><Info l="Responsável de origem" v={selected.responsible_name}/><Info l="Prazo" v={formatDateTime(selected.relevant_at)}/><Info l="Situação original" v={selected.source_status}/><Info l="Último movimento" v={formatDateTime(selected.last_movement_at)}/></dl>{canFollowUp&&<><div><Label>Status do acompanhamento</Label><Filter value={selected.monitoring_status} set={v=>act(()=>actions.changeStatus(selected,v as MonitoringStatus),v==="novo"?"Alerta reaberto.":"Acompanhamento atualizado.")} label="Status" values={Object.entries(statusLabel).filter(([value])=>canAdminMonitoring || ["em_analise","acompanhado"].includes(value))} all={false}/></div>{canAdminMonitoring&&<><div><Label>Prioridade manual</Label><Filter value={selected.priority_override??"automatica"} set={v=>act(()=>actions.priority(selected,v==="automatica"?null:v as MonitoringPriority),"Prioridade atualizada.")} label="Prioridade" values={[["automatica","Automática"],...Object.entries(priorityLabel)]} all={false}/></div><div><Label>Responsável pelo acompanhamento</Label><Filter value={selected.assigned_to??"none"} set={v=>act(()=>actions.assign(selected,v==="none"?null:v),"Responsável atualizado.")} label="Responsável" values={[["none","Não atribuído"],...(team.data??[]).map(m=>[m.user_id,m.full_name??m.email??"Membro"])]} all={false}/></div></>}<Note onSave={n=>act(()=>actions.addNote(selected,n),"Nota adicionada.")}/></>}{selected.notes&&<div><Label>Notas internas</Label><p className="mt-1 whitespace-pre-wrap rounded-md bg-muted p-3 text-sm">{selected.notes}</p></div>}<Button asChild variant="outline"><a href={sourcePath(selected)}><ExternalLink className="size-4"/> Abrir registro original</a></Button></div>}</SheetContent></Sheet>
  </div>;
}
function Filter({value,set,label,values,all=true}:{value:string;set:(v:string)=>void;label:string;values:string[][];all?:boolean}){return <Select value={value} onValueChange={set}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{all&&<SelectItem value={ALL}>Todos</SelectItem>}{values.map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select>}
function Info({l,v}:{l:string;v:string|null|undefined}){return <div><dt className="text-xs text-muted-foreground">{l}</dt><dd>{v||"—"}</dd></div>}
function Note({onSave}:{onSave:(n:string)=>Promise<void>}){const [note,setNote]=useState("");return <div className="space-y-2"><Label>Adicionar nota interna</Label><Textarea maxLength={2000} value={note} onChange={e=>setNote(e.target.value)} placeholder="Registre a ação de acompanhamento…"/><Button size="sm" disabled={!note.trim()} onClick={async()=>{await onSave(note);setNote("")}}>Adicionar nota</Button></div>}
