import { useMemo, useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { Archive, CalendarDays, History, LayoutGrid, List, MessageSquare, Pencil, Plus, RotateCcw } from "lucide-react";
import { toast } from "sonner";
import { useWorkspace } from "@/lib/workspace";
import { usePermissions } from "@/lib/permissions";
import { useClients, useProcesses } from "@/hooks/use-operations";
import { useTeamMembers } from "@/hooks/use-team";
import { useAddTaskComment, useArchiveTask, useChangeTaskStatus, useSaveTask, useTaskComments, useTaskHistory, useTaskList, type TaskFormValues, type TaskRow } from "@/hooks/use-tasks";
import { PRIORITY, TASK_BOARD_STATUSES, TASK_STATUS, type PriorityLevel, type TaskStatus } from "@/lib/domain";
import { filterTasks, groupTasksByStatus, taskDateKey, taskIndicators } from "@/lib/tasks";
import { describeError } from "@/lib/errors";
import { formatDate, formatDateOnly } from "@/lib/format";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { StatusBadge } from "@/components/shared/status-badge";

export const Route = createFileRoute("/_authenticated/tarefas")({ component: TasksPage });
type View = "list" | "board" | "calendar";
const blank: TaskFormValues = { title: "", description: "", priority: "media", status: "pendente", due_at: "", assignee_id: "", assignee_name: "", client_id: "", process_id: "", document_id: "", monitoring_item_id: "" };

function TasksPage() {
  const { organizationId } = useWorkspace();
  const permissions = usePermissions();
  const tasks = useTaskList(organizationId, undefined, true);
  const clients = useClients(organizationId); const processes = useProcesses(organizationId); const team = useTeamMembers(organizationId);
  const save = useSaveTask(organizationId); const changeStatus = useChangeTaskStatus(organizationId); const archive = useArchiveTask(organizationId);
  const [view, setView] = useState<View>("list"); const [status, setStatus] = useState<TaskStatus | "open" | "all">("open"); const [priority, setPriority] = useState<PriorityLevel | "all">("all"); const [showArchived, setShowArchived] = useState(false);
  const [editing, setEditing] = useState<TaskRow | "new" | null>(null); const [detail, setDetail] = useState<TaskRow | null>(null);
  const [form, setForm] = useState<TaskFormValues>(blank); const rows = filterTasks(tasks.data ?? [], { status, priority, archived: showArchived });
  const indicators = taskIndicators(tasks.data ?? []); const columns = groupTasksByStatus(rows); const owners = team.data ?? [];
  const openForm = (task?: TaskRow) => { setEditing(task ?? "new"); setForm(task ? { ...task } : blank); };
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (form.title.trim().length < 3) return toast.error("Informe um título com pelo menos três caracteres."); try { await save.mutateAsync({ id: editing === "new" ? undefined : editing?.id, values: { ...form, title: form.title.trim() } }); toast.success(editing === "new" ? "Tarefa criada." : "Tarefa atualizada."); setEditing(null); } catch (error) { toast.error(describeError(error, "tarefa")); } };
  const updateStatus = async (task: TaskRow, next: TaskStatus) => { try { await changeStatus.mutateAsync({ task, status: next }); toast.success(next === "concluida" ? "Tarefa concluída." : "Status atualizado."); } catch (error) { toast.error(describeError(error, "tarefa")); } };
  return <div className="mx-auto w-full max-w-7xl space-y-5 p-4 sm:p-6">
    <header className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="page-title">Tarefas</h1><p className="page-subtitle">Lista, quadro e agenda operacional da sua organização.</p></div>{permissions.canManageTasks && <Button onClick={() => openForm()}><Plus className="mr-2 size-4"/>Nova tarefa</Button>}</header>
    <section className="grid grid-cols-2 gap-3 md:grid-cols-4">{[["Em aberto", indicators.open],["Atrasadas", indicators.overdue],["Concluídas", indicators.completed],["Arquivadas", indicators.archived]].map(([label,value]) => <Card key={label}><CardContent className="p-4"><p className="field-label">{label}</p><p className="metric-value mt-2">{value}</p></CardContent></Card>)}</section>
    <div className="flex flex-wrap gap-2"><Tabs value={view} onValueChange={(v) => setView(v as View)}><TabsList><TabsTrigger value="list"><List className="mr-2 size-4"/>Lista</TabsTrigger><TabsTrigger value="board"><LayoutGrid className="mr-2 size-4"/>Quadro</TabsTrigger><TabsTrigger value="calendar"><CalendarDays className="mr-2 size-4"/>Agenda</TabsTrigger></TabsList></Tabs>
      <Select value={status} onValueChange={(v) => setStatus(v as typeof status)}><SelectTrigger className="w-44"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="open">Em aberto</SelectItem><SelectItem value="all">Todos os status</SelectItem>{Object.entries(TASK_STATUS).map(([k,v]) => <SelectItem key={k} value={k}>{v.label}</SelectItem>)}</SelectContent></Select>
      <Select value={priority} onValueChange={(v) => setPriority(v as typeof priority)}><SelectTrigger className="w-44"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">Todas prioridades</SelectItem>{Object.entries(PRIORITY).map(([k,v]) => <SelectItem key={k} value={k}>{v.label}</SelectItem>)}</SelectContent></Select>
      <Button variant={showArchived ? "secondary" : "outline"} onClick={() => setShowArchived(!showArchived)}><Archive className="mr-2 size-4"/>{showArchived ? "Arquivadas" : "Ver arquivadas"}</Button></div>
    {tasks.isLoading ? <Card><CardContent className="p-8">Carregando tarefas…</CardContent></Card> : view === "board" ? <div className="grid gap-3 lg:grid-cols-4">{TASK_BOARD_STATUSES.map(col => <Card key={col}><CardContent className="p-3"><h2 className="mb-3 font-semibold">{TASK_STATUS[col].label} <Badge variant="secondary">{columns[col].length}</Badge></h2><div className="space-y-2">{columns[col].map(task => <TaskCard key={task.id} task={task} onOpen={setDetail}/>)}</div></CardContent></Card>)}</div> : view === "calendar" ? <Agenda rows={rows} onOpen={setDetail}/> : <Card><CardContent className="divide-y p-0">{rows.length ? rows.map(task => <div key={task.id} className="flex flex-wrap items-center gap-3 p-4"><input type="checkbox" aria-label={`Concluir ${task.title}`} disabled={!permissions.canManageTasks} checked={task.status === "concluida"} onChange={e => updateStatus(task, e.target.checked ? "concluida" : "pendente")}/><button className="min-w-0 flex-1 text-left" onClick={() => setDetail(task)}><span className="block truncate font-medium">{task.title}</span><span className="helper-text">{task.clients?.name ?? "Sem cliente"} · {task.assignee_name ?? "Sem responsável"}</span></button><StatusBadge {...PRIORITY[task.priority]}/><span className="text-sm">{formatDateOnly(task.due_at)}</span>{permissions.canManageTasks && <><Button size="icon" variant="ghost" aria-label="Editar" onClick={() => openForm(task)}><Pencil className="size-4"/></Button><Button size="icon" variant="ghost" aria-label={task.archived_at ? "Restaurar" : "Arquivar"} onClick={() => archive.mutate({ task, archived: !task.archived_at })}>{task.archived_at ? <RotateCcw className="size-4"/> : <Archive className="size-4"/>}</Button></>}</div>) : <p className="p-8 text-center text-muted-foreground">Nenhuma tarefa encontrada.</p>}</CardContent></Card>}
    <TaskForm open={Boolean(editing)} onOpenChange={(o: boolean) => !o && setEditing(null)} form={form} setForm={setForm} onSubmit={submit} clients={clients.data ?? []} processes={processes.data ?? []} owners={owners} pending={save.isPending}/>
    <TaskDetail task={detail} onClose={() => setDetail(null)} onStatus={updateStatus}/>
  </div>;
}
function TaskCard({task,onOpen}:{task:TaskRow;onOpen:(t:TaskRow)=>void}) { return <button onClick={() => onOpen(task)} className="w-full rounded-lg border bg-background p-3 text-left hover:border-brand"><p className="font-medium">{task.title}</p><p className="helper-text mt-2">{formatDateOnly(task.due_at)} · {PRIORITY[task.priority].label}</p></button>; }
function Agenda({rows,onOpen}:{rows:TaskRow[];onOpen:(t:TaskRow)=>void}) { const groups = rows.filter((t) => taskDateKey(t.due_at)).reduce((map, t) => { const key = taskDateKey(t.due_at)!; map.set(key, [...(map.get(key) ?? []), t]); return map; }, new Map<string, TaskRow[]>()); return <Card><CardContent className="space-y-5 p-5">{[...groups.entries()].sort().map(([day,items]) => <section key={day}><h2 className="mb-2 font-semibold">{formatDateOnly(day)}</h2>{items.map(t => <button key={t.id} className="mb-2 block w-full rounded border p-3 text-left" onClick={() => onOpen(t)}>{t.due_time?.slice(0,5) ?? "Dia todo"} · {t.title}</button>)}</section>)}{!groups.size && <p className="text-muted-foreground">Nenhuma tarefa com prazo nesta seleção.</p>}</CardContent></Card>; }
function TaskForm({open,onOpenChange,form,setForm,onSubmit,clients,processes,owners,pending}:any) { return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{form.id ? "Editar tarefa" : "Nova tarefa"}</DialogTitle></DialogHeader><form className="grid gap-4 sm:grid-cols-2" onSubmit={onSubmit}><div className="sm:col-span-2"><Label>Título</Label><Input value={form.title} maxLength={160} onChange={e=>setForm({...form,title:e.target.value})}/></div><div className="sm:col-span-2"><Label>Descrição</Label><Textarea value={form.description??""} onChange={e=>setForm({...form,description:e.target.value})}/></div><FieldSelect label="Status" value={form.status??"pendente"} entries={TASK_STATUS} onChange={(v:string)=>setForm({...form,status:v})}/><FieldSelect label="Prioridade" value={form.priority} entries={PRIORITY} onChange={(v:string)=>setForm({...form,priority:v})}/><div><Label>Prazo</Label><Input type="date" value={form.due_at?.slice(0,10)??""} onChange={e=>setForm({...form,due_at:e.target.value})}/></div><div><Label>Responsável</Label><Select value={form.assignee_id||"none"} onValueChange={v=>{const m=owners.find((x:any)=>x.user_id===v);setForm({...form,assignee_id:v==="none"?null:v,assignee_name:m?.full_name??m?.email??null})}}><SelectTrigger><SelectValue placeholder="Sem responsável"/></SelectTrigger><SelectContent><SelectItem value="none">Sem responsável</SelectItem>{owners.map((m:any)=><SelectItem key={m.user_id} value={m.user_id}>{m.full_name??m.email}</SelectItem>)}</SelectContent></Select></div><Relation label="Cliente" value={form.client_id} items={clients.map((x:any)=>({id:x.id,label:x.name}))} onChange={(v:string)=>setForm({...form,client_id:v})}/><Relation label="Processo" value={form.process_id} items={processes.map((x:any)=>({id:x.id,label:x.code}))} onChange={(v:string)=>setForm({...form,process_id:v})}/><div><Label>Documento (ID)</Label><Input value={form.document_id??""} onChange={e=>setForm({...form,document_id:e.target.value||null})}/></div><div><Label>Monitoramento (ID)</Label><Input value={form.monitoring_item_id??""} onChange={e=>setForm({...form,monitoring_item_id:e.target.value||null})}/></div><div className="sm:col-span-2 flex justify-end"><Button disabled={pending}>Salvar tarefa</Button></div></form></DialogContent></Dialog>; }
function FieldSelect({label,value,entries,onChange}:any){return <div><Label>{label}</Label><Select value={value} onValueChange={onChange}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{Object.entries(entries).map(([k,v]:any)=><SelectItem key={k} value={k}>{v.label}</SelectItem>)}</SelectContent></Select></div>}
function Relation({label,value,items,onChange}:any){return <div><Label>{label}</Label><Select value={value||"none"} onValueChange={(v)=>onChange(v==="none"?null:v)}><SelectTrigger><SelectValue placeholder="Sem vínculo"/></SelectTrigger><SelectContent><SelectItem value="none">Sem vínculo</SelectItem>{items.map((x:any)=><SelectItem key={x.id} value={x.id}>{x.label}</SelectItem>)}</SelectContent></Select></div>}
function TaskDetail({task,onClose,onStatus}:{task:TaskRow|null;onClose:()=>void;onStatus:(t:TaskRow,s:TaskStatus)=>void}) { const {organizationId}=useWorkspace(); const comments=useTaskComments(task?.id??null); const history=useTaskHistory(task?.id??null); const add=useAddTaskComment(organizationId); const [comment,setComment]=useState(""); return <Dialog open={Boolean(task)} onOpenChange={o=>!o&&onClose()}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl">{task&&<><DialogHeader><DialogTitle>{task.title}</DialogTitle></DialogHeader><div className="flex flex-wrap gap-2"><StatusBadge {...TASK_STATUS[task.status]}/>{TASK_BOARD_STATUSES.map(s=><Button key={s} size="sm" variant="outline" onClick={()=>onStatus(task,s)}>{TASK_STATUS[s].label}</Button>)}</div><p className="text-sm">{task.description||"Sem descrição."}</p>{task.client_id&&<Link to="/clientes/$clientId" params={{clientId:task.client_id}} className="text-sm text-brand">Abrir cliente vinculado</Link>}<section><h3 className="mb-2 flex items-center font-semibold"><MessageSquare className="mr-2 size-4"/>Comentários</h3>{comments.data?.map(c=><p key={c.id} className="mb-2 rounded border p-2 text-sm"><b>{c.user_name??"Usuário"}</b>: {c.comment}</p>)}<form className="flex gap-2" onSubmit={async e=>{e.preventDefault();if(!comment.trim())return;await add.mutateAsync({taskId:task.id,comment:comment.trim()});setComment("")}}><Input value={comment} onChange={e=>setComment(e.target.value)} placeholder="Adicionar comentário"/><Button>Enviar</Button></form></section><section><h3 className="mb-2 flex items-center font-semibold"><History className="mr-2 size-4"/>Histórico</h3>{history.data?.map(h=><p key={h.id} className="text-sm text-muted-foreground">{formatDate(h.created_at)} · {h.user_name??"Sistema"} · {h.action}</p>)}</section></>}</DialogContent></Dialog>; }
