/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as AuthenticatedAdministracaoPlataformaRouteImport } from './routes/_authenticated/administracao-plataforma'
import { Route as AuthenticatedAjudaRouteImport } from './routes/_authenticated/ajuda'
import { Route as AuthenticatedAutomacoesRouteImport } from './routes/_authenticated/automacoes'
import { Route as AuthenticatedCentralRouteImport } from './routes/_authenticated/central'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedComunicacaoRouteImport } from './routes/_authenticated/comunicacao'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated/documentos'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedMonitoramentoRouteImport } from './routes/_authenticated/monitoramento'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedNovidadesRouteImport } from './routes/_authenticated/novidades'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedProcessosRouteImport } from './routes/_authenticated/processos'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedTarefasRouteImport } from './routes/_authenticated/tarefas'
import { Route as ConviteTokenRouteImport } from './routes/convite.$token'
import { Route as AuthenticatedClientesIndexRouteImport } from './routes/_authenticated/clientes.index'
import { Route as AuthenticatedClientesClientIdRouteImport } from './routes/_authenticated/clientes.$clientId'
import { Route as AuthenticatedClientesNovoRouteImport } from './routes/_authenticated/clientes.novo'
import { Route as AuthenticatedProcessosIndexRouteImport } from './routes/_authenticated/processos.index'
import { Route as AuthenticatedProcessosProcessIdRouteImport } from './routes/_authenticated/processos.$processId'
import { Route as AuthenticatedProcessosNovoRouteImport } from './routes/_authenticated/processos.novo'
import { Route as AuthenticatedClientesClientIdEditarRouteImport } from './routes/_authenticated/clientes.$clientId_.editar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdministracaoPlataformaRoute =
  AuthenticatedAdministracaoPlataformaRouteImport.update({
    id: '/administracao-plataforma',
    path: '/administracao-plataforma',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAjudaRoute = AuthenticatedAjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAutomacoesRoute = AuthenticatedAutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCentralRoute = AuthenticatedCentralRouteImport.update({
  id: '/central',
  path: '/central',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedComunicacaoRoute =
  AuthenticatedComunicacaoRouteImport.update({
    id: '/comunicacao',
    path: '/comunicacao',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMonitoramentoRoute =
  AuthenticatedMonitoramentoRouteImport.update({
    id: '/monitoramento',
    path: '/monitoramento',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNovidadesRoute = AuthenticatedNovidadesRouteImport.update({
  id: '/novidades',
  path: '/novidades',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProcessosRoute = AuthenticatedProcessosRouteImport.update({
  id: '/processos',
  path: '/processos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTarefasRoute = AuthenticatedTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ConviteTokenRoute = ConviteTokenRouteImport.update({
  id: '/convite/$token',
  path: '/convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClientesIndexRoute =
  AuthenticatedClientesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientesRoute,
  } as any)
const AuthenticatedClientesClientIdRoute =
  AuthenticatedClientesClientIdRouteImport.update({
    id: '/$clientId',
    path: '/$clientId',
    getParentRoute: () => AuthenticatedClientesRoute,
  } as any)
const AuthenticatedClientesNovoRoute =
  AuthenticatedClientesNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedClientesRoute,
  } as any)
const AuthenticatedProcessosIndexRoute =
  AuthenticatedProcessosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProcessosRoute,
  } as any)
const AuthenticatedProcessosProcessIdRoute =
  AuthenticatedProcessosProcessIdRouteImport.update({
    id: '/$processId',
    path: '/$processId',
    getParentRoute: () => AuthenticatedProcessosRoute,
  } as any)
const AuthenticatedProcessosNovoRoute =
  AuthenticatedProcessosNovoRouteImport.update({
    id: '/novo',
    path: '/novo',
    getParentRoute: () => AuthenticatedProcessosRoute,
  } as any)
const AuthenticatedClientesClientIdEditarRoute =
  AuthenticatedClientesClientIdEditarRouteImport.update({
    id: '/$clientId_/editar',
    path: '/$clientId/editar',
    getParentRoute: () => AuthenticatedClientesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/administracao-plataforma': typeof AuthenticatedAdministracaoPlataformaRoute
  '/ajuda': typeof AuthenticatedAjudaRoute
  '/automacoes': typeof AuthenticatedAutomacoesRoute
  '/central': typeof AuthenticatedCentralRoute
  '/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/comunicacao': typeof AuthenticatedComunicacaoRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/monitoramento': typeof AuthenticatedMonitoramentoRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/novidades': typeof AuthenticatedNovidadesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/processos': typeof AuthenticatedProcessosRouteWithChildren
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/clientes/$clientId': typeof AuthenticatedClientesClientIdRoute
  '/clientes/novo': typeof AuthenticatedClientesNovoRoute
  '/processos/$processId': typeof AuthenticatedProcessosProcessIdRoute
  '/processos/novo': typeof AuthenticatedProcessosNovoRoute
  '/clientes/': typeof AuthenticatedClientesIndexRoute
  '/processos/': typeof AuthenticatedProcessosIndexRoute
  '/clientes/$clientId/editar': typeof AuthenticatedClientesClientIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/administracao-plataforma': typeof AuthenticatedAdministracaoPlataformaRoute
  '/ajuda': typeof AuthenticatedAjudaRoute
  '/automacoes': typeof AuthenticatedAutomacoesRoute
  '/central': typeof AuthenticatedCentralRoute
  '/comunicacao': typeof AuthenticatedComunicacaoRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/monitoramento': typeof AuthenticatedMonitoramentoRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/novidades': typeof AuthenticatedNovidadesRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/clientes/$clientId': typeof AuthenticatedClientesClientIdRoute
  '/clientes/novo': typeof AuthenticatedClientesNovoRoute
  '/processos/$processId': typeof AuthenticatedProcessosProcessIdRoute
  '/processos/novo': typeof AuthenticatedProcessosNovoRoute
  '/clientes': typeof AuthenticatedClientesIndexRoute
  '/processos': typeof AuthenticatedProcessosIndexRoute
  '/clientes/$clientId/editar': typeof AuthenticatedClientesClientIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/_authenticated/administracao-plataforma': typeof AuthenticatedAdministracaoPlataformaRoute
  '/_authenticated/ajuda': typeof AuthenticatedAjudaRoute
  '/_authenticated/automacoes': typeof AuthenticatedAutomacoesRoute
  '/_authenticated/central': typeof AuthenticatedCentralRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/_authenticated/comunicacao': typeof AuthenticatedComunicacaoRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/documentos': typeof AuthenticatedDocumentosRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/monitoramento': typeof AuthenticatedMonitoramentoRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/novidades': typeof AuthenticatedNovidadesRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/processos': typeof AuthenticatedProcessosRouteWithChildren
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/tarefas': typeof AuthenticatedTarefasRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/_authenticated/clientes/$clientId': typeof AuthenticatedClientesClientIdRoute
  '/_authenticated/clientes/novo': typeof AuthenticatedClientesNovoRoute
  '/_authenticated/processos/$processId': typeof AuthenticatedProcessosProcessIdRoute
  '/_authenticated/processos/novo': typeof AuthenticatedProcessosNovoRoute
  '/_authenticated/clientes/': typeof AuthenticatedClientesIndexRoute
  '/_authenticated/processos/': typeof AuthenticatedProcessosIndexRoute
  '/_authenticated/clientes/$clientId_/editar': typeof AuthenticatedClientesClientIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/entrar'
    | '/politica-de-privacidade'
    | '/redefinir-senha'
    | '/termos-de-uso'
    | '/administracao-plataforma'
    | '/ajuda'
    | '/automacoes'
    | '/central'
    | '/clientes'
    | '/comunicacao'
    | '/configuracoes'
    | '/documentos'
    | '/equipe'
    | '/financeiro'
    | '/monitoramento'
    | '/notificacoes'
    | '/novidades'
    | '/onboarding'
    | '/processos'
    | '/relatorios'
    | '/tarefas'
    | '/convite/$token'
    | '/clientes/$clientId'
    | '/clientes/novo'
    | '/processos/$processId'
    | '/processos/novo'
    | '/clientes/'
    | '/processos/'
    | '/clientes/$clientId/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/entrar'
    | '/politica-de-privacidade'
    | '/redefinir-senha'
    | '/termos-de-uso'
    | '/administracao-plataforma'
    | '/ajuda'
    | '/automacoes'
    | '/central'
    | '/comunicacao'
    | '/configuracoes'
    | '/documentos'
    | '/equipe'
    | '/financeiro'
    | '/monitoramento'
    | '/notificacoes'
    | '/novidades'
    | '/onboarding'
    | '/relatorios'
    | '/tarefas'
    | '/convite/$token'
    | '/clientes/$clientId'
    | '/clientes/novo'
    | '/processos/$processId'
    | '/processos/novo'
    | '/clientes'
    | '/processos'
    | '/clientes/$clientId/editar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/entrar'
    | '/politica-de-privacidade'
    | '/redefinir-senha'
    | '/termos-de-uso'
    | '/_authenticated/administracao-plataforma'
    | '/_authenticated/ajuda'
    | '/_authenticated/automacoes'
    | '/_authenticated/central'
    | '/_authenticated/clientes'
    | '/_authenticated/comunicacao'
    | '/_authenticated/configuracoes'
    | '/_authenticated/documentos'
    | '/_authenticated/equipe'
    | '/_authenticated/financeiro'
    | '/_authenticated/monitoramento'
    | '/_authenticated/notificacoes'
    | '/_authenticated/novidades'
    | '/_authenticated/onboarding'
    | '/_authenticated/processos'
    | '/_authenticated/relatorios'
    | '/_authenticated/tarefas'
    | '/convite/$token'
    | '/_authenticated/clientes/$clientId'
    | '/_authenticated/clientes/novo'
    | '/_authenticated/processos/$processId'
    | '/_authenticated/processos/novo'
    | '/_authenticated/clientes/'
    | '/_authenticated/processos/'
    | '/_authenticated/clientes/$clientId_/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  EntrarRoute: typeof EntrarRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  ConviteTokenRoute: typeof ConviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/administracao-plataforma': {
      id: '/_authenticated/administracao-plataforma'
      path: '/administracao-plataforma'
      fullPath: '/administracao-plataforma'
      preLoaderRoute: typeof AuthenticatedAdministracaoPlataformaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ajuda': {
      id: '/_authenticated/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AuthenticatedAjudaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/automacoes': {
      id: '/_authenticated/automacoes'
      path: '/automacoes'
      fullPath: '/automacoes'
      preLoaderRoute: typeof AuthenticatedAutomacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/central': {
      id: '/_authenticated/central'
      path: '/central'
      fullPath: '/central'
      preLoaderRoute: typeof AuthenticatedCentralRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comunicacao': {
      id: '/_authenticated/comunicacao'
      path: '/comunicacao'
      fullPath: '/comunicacao'
      preLoaderRoute: typeof AuthenticatedComunicacaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documentos': {
      id: '/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/monitoramento': {
      id: '/_authenticated/monitoramento'
      path: '/monitoramento'
      fullPath: '/monitoramento'
      preLoaderRoute: typeof AuthenticatedMonitoramentoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/novidades': {
      id: '/_authenticated/novidades'
      path: '/novidades'
      fullPath: '/novidades'
      preLoaderRoute: typeof AuthenticatedNovidadesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/processos': {
      id: '/_authenticated/processos'
      path: '/processos'
      fullPath: '/processos'
      preLoaderRoute: typeof AuthenticatedProcessosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tarefas': {
      id: '/_authenticated/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AuthenticatedTarefasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/convite/$token': {
      id: '/convite/$token'
      path: '/convite/$token'
      fullPath: '/convite/$token'
      preLoaderRoute: typeof ConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clientes/': {
      id: '/_authenticated/clientes/'
      path: '/'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AuthenticatedClientesIndexRouteImport
      parentRoute: typeof AuthenticatedClientesRoute
    }
    '/_authenticated/clientes/$clientId': {
      id: '/_authenticated/clientes/$clientId'
      path: '/$clientId'
      fullPath: '/clientes/$clientId'
      preLoaderRoute: typeof AuthenticatedClientesClientIdRouteImport
      parentRoute: typeof AuthenticatedClientesRoute
    }
    '/_authenticated/clientes/novo': {
      id: '/_authenticated/clientes/novo'
      path: '/novo'
      fullPath: '/clientes/novo'
      preLoaderRoute: typeof AuthenticatedClientesNovoRouteImport
      parentRoute: typeof AuthenticatedClientesRoute
    }
    '/_authenticated/processos/': {
      id: '/_authenticated/processos/'
      path: '/'
      fullPath: '/processos/'
      preLoaderRoute: typeof AuthenticatedProcessosIndexRouteImport
      parentRoute: typeof AuthenticatedProcessosRoute
    }
    '/_authenticated/processos/$processId': {
      id: '/_authenticated/processos/$processId'
      path: '/$processId'
      fullPath: '/processos/$processId'
      preLoaderRoute: typeof AuthenticatedProcessosProcessIdRouteImport
      parentRoute: typeof AuthenticatedProcessosRoute
    }
    '/_authenticated/processos/novo': {
      id: '/_authenticated/processos/novo'
      path: '/novo'
      fullPath: '/processos/novo'
      preLoaderRoute: typeof AuthenticatedProcessosNovoRouteImport
      parentRoute: typeof AuthenticatedProcessosRoute
    }
    '/_authenticated/clientes/$clientId_/editar': {
      id: '/_authenticated/clientes/$clientId_/editar'
      path: '/$clientId/editar'
      fullPath: '/clientes/$clientId/editar'
      preLoaderRoute: typeof AuthenticatedClientesClientIdEditarRouteImport
      parentRoute: typeof AuthenticatedClientesRoute
    }
  }
}

interface AuthenticatedClientesRouteChildren {
  AuthenticatedClientesClientIdRoute: typeof AuthenticatedClientesClientIdRoute
  AuthenticatedClientesNovoRoute: typeof AuthenticatedClientesNovoRoute
  AuthenticatedClientesIndexRoute: typeof AuthenticatedClientesIndexRoute
  AuthenticatedClientesClientIdEditarRoute: typeof AuthenticatedClientesClientIdEditarRoute
}

const AuthenticatedClientesRouteChildren: AuthenticatedClientesRouteChildren = {
  AuthenticatedClientesClientIdRoute: AuthenticatedClientesClientIdRoute,
  AuthenticatedClientesNovoRoute: AuthenticatedClientesNovoRoute,
  AuthenticatedClientesIndexRoute: AuthenticatedClientesIndexRoute,
  AuthenticatedClientesClientIdEditarRoute:
    AuthenticatedClientesClientIdEditarRoute,
}

const AuthenticatedClientesRouteWithChildren =
  AuthenticatedClientesRoute._addFileChildren(
    AuthenticatedClientesRouteChildren,
  )

interface AuthenticatedProcessosRouteChildren {
  AuthenticatedProcessosProcessIdRoute: typeof AuthenticatedProcessosProcessIdRoute
  AuthenticatedProcessosNovoRoute: typeof AuthenticatedProcessosNovoRoute
  AuthenticatedProcessosIndexRoute: typeof AuthenticatedProcessosIndexRoute
}

const AuthenticatedProcessosRouteChildren: AuthenticatedProcessosRouteChildren =
  {
    AuthenticatedProcessosProcessIdRoute: AuthenticatedProcessosProcessIdRoute,
    AuthenticatedProcessosNovoRoute: AuthenticatedProcessosNovoRoute,
    AuthenticatedProcessosIndexRoute: AuthenticatedProcessosIndexRoute,
  }

const AuthenticatedProcessosRouteWithChildren =
  AuthenticatedProcessosRoute._addFileChildren(
    AuthenticatedProcessosRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdministracaoPlataformaRoute: typeof AuthenticatedAdministracaoPlataformaRoute
  AuthenticatedAjudaRoute: typeof AuthenticatedAjudaRoute
  AuthenticatedAutomacoesRoute: typeof AuthenticatedAutomacoesRoute
  AuthenticatedCentralRoute: typeof AuthenticatedCentralRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRouteWithChildren
  AuthenticatedComunicacaoRoute: typeof AuthenticatedComunicacaoRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedMonitoramentoRoute: typeof AuthenticatedMonitoramentoRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedNovidadesRoute: typeof AuthenticatedNovidadesRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProcessosRoute: typeof AuthenticatedProcessosRouteWithChildren
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedTarefasRoute: typeof AuthenticatedTarefasRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdministracaoPlataformaRoute:
    AuthenticatedAdministracaoPlataformaRoute,
  AuthenticatedAjudaRoute: AuthenticatedAjudaRoute,
  AuthenticatedAutomacoesRoute: AuthenticatedAutomacoesRoute,
  AuthenticatedCentralRoute: AuthenticatedCentralRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRouteWithChildren,
  AuthenticatedComunicacaoRoute: AuthenticatedComunicacaoRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedMonitoramentoRoute: AuthenticatedMonitoramentoRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedNovidadesRoute: AuthenticatedNovidadesRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProcessosRoute: AuthenticatedProcessosRouteWithChildren,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedTarefasRoute: AuthenticatedTarefasRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  EntrarRoute: EntrarRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  ConviteTokenRoute: ConviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
