/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTarefasRouteImport } from './routes/_authenticated/tarefas'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedNovidadesRouteImport } from './routes/_authenticated/novidades'
import { Route as AuthenticatedMonitoramentoRouteImport } from './routes/_authenticated/monitoramento'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedEquipeRouteImport } from './routes/_authenticated/equipe'
import { Route as AuthenticatedDocumentosRouteImport } from './routes/_authenticated/documentos'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedComunicacaoRouteImport } from './routes/_authenticated/comunicacao'
import { Route as AuthenticatedAutomacoesRouteImport } from './routes/_authenticated/automacoes'
import { Route as AuthenticatedAjudaRouteImport } from './routes/_authenticated/ajuda'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTarefasRoute = AuthenticatedTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNovidadesRoute = AuthenticatedNovidadesRouteImport.update({
  id: '/novidades',
  path: '/novidades',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMonitoramentoRoute =
  AuthenticatedMonitoramentoRouteImport.update({
    id: '/monitoramento',
    path: '/monitoramento',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEquipeRoute = AuthenticatedEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocumentosRoute = AuthenticatedDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedComunicacaoRoute =
  AuthenticatedComunicacaoRouteImport.update({
    id: '/comunicacao',
    path: '/comunicacao',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAutomacoesRoute = AuthenticatedAutomacoesRouteImport.update({
  id: '/automacoes',
  path: '/automacoes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAjudaRoute = AuthenticatedAjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajuda': typeof AuthenticatedAjudaRoute
  '/automacoes': typeof AuthenticatedAutomacoesRoute
  '/comunicacao': typeof AuthenticatedComunicacaoRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/monitoramento': typeof AuthenticatedMonitoramentoRoute
  '/novidades': typeof AuthenticatedNovidadesRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajuda': typeof AuthenticatedAjudaRoute
  '/automacoes': typeof AuthenticatedAutomacoesRoute
  '/comunicacao': typeof AuthenticatedComunicacaoRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/documentos': typeof AuthenticatedDocumentosRoute
  '/equipe': typeof AuthenticatedEquipeRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/monitoramento': typeof AuthenticatedMonitoramentoRoute
  '/novidades': typeof AuthenticatedNovidadesRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/ajuda': typeof AuthenticatedAjudaRoute
  '/_authenticated/automacoes': typeof AuthenticatedAutomacoesRoute
  '/_authenticated/comunicacao': typeof AuthenticatedComunicacaoRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/documentos': typeof AuthenticatedDocumentosRoute
  '/_authenticated/equipe': typeof AuthenticatedEquipeRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/monitoramento': typeof AuthenticatedMonitoramentoRoute
  '/_authenticated/novidades': typeof AuthenticatedNovidadesRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/tarefas': typeof AuthenticatedTarefasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajuda'
    | '/automacoes'
    | '/comunicacao'
    | '/configuracoes'
    | '/documentos'
    | '/equipe'
    | '/financeiro'
    | '/monitoramento'
    | '/novidades'
    | '/relatorios'
    | '/tarefas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajuda'
    | '/automacoes'
    | '/comunicacao'
    | '/configuracoes'
    | '/documentos'
    | '/equipe'
    | '/financeiro'
    | '/monitoramento'
    | '/novidades'
    | '/relatorios'
    | '/tarefas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/ajuda'
    | '/_authenticated/automacoes'
    | '/_authenticated/comunicacao'
    | '/_authenticated/configuracoes'
    | '/_authenticated/documentos'
    | '/_authenticated/equipe'
    | '/_authenticated/financeiro'
    | '/_authenticated/monitoramento'
    | '/_authenticated/novidades'
    | '/_authenticated/relatorios'
    | '/_authenticated/tarefas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tarefas': {
      id: '/_authenticated/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AuthenticatedTarefasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/novidades': {
      id: '/_authenticated/novidades'
      path: '/novidades'
      fullPath: '/novidades'
      preLoaderRoute: typeof AuthenticatedNovidadesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/monitoramento': {
      id: '/_authenticated/monitoramento'
      path: '/monitoramento'
      fullPath: '/monitoramento'
      preLoaderRoute: typeof AuthenticatedMonitoramentoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/equipe': {
      id: '/_authenticated/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof AuthenticatedEquipeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documentos': {
      id: '/_authenticated/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof AuthenticatedDocumentosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/comunicacao': {
      id: '/_authenticated/comunicacao'
      path: '/comunicacao'
      fullPath: '/comunicacao'
      preLoaderRoute: typeof AuthenticatedComunicacaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/automacoes': {
      id: '/_authenticated/automacoes'
      path: '/automacoes'
      fullPath: '/automacoes'
      preLoaderRoute: typeof AuthenticatedAutomacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ajuda': {
      id: '/_authenticated/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AuthenticatedAjudaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAjudaRoute: typeof AuthenticatedAjudaRoute
  AuthenticatedAutomacoesRoute: typeof AuthenticatedAutomacoesRoute
  AuthenticatedComunicacaoRoute: typeof AuthenticatedComunicacaoRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDocumentosRoute: typeof AuthenticatedDocumentosRoute
  AuthenticatedEquipeRoute: typeof AuthenticatedEquipeRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedMonitoramentoRoute: typeof AuthenticatedMonitoramentoRoute
  AuthenticatedNovidadesRoute: typeof AuthenticatedNovidadesRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedTarefasRoute: typeof AuthenticatedTarefasRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAjudaRoute: AuthenticatedAjudaRoute,
  AuthenticatedAutomacoesRoute: AuthenticatedAutomacoesRoute,
  AuthenticatedComunicacaoRoute: AuthenticatedComunicacaoRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDocumentosRoute: AuthenticatedDocumentosRoute,
  AuthenticatedEquipeRoute: AuthenticatedEquipeRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedMonitoramentoRoute: AuthenticatedMonitoramentoRoute,
  AuthenticatedNovidadesRoute: AuthenticatedNovidadesRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedTarefasRoute: AuthenticatedTarefasRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
