-- Marcador de compatibilidade para a versão registrada pelo Lovable Cloud.
--
-- O conteúdo anterior duplicava as migrations 20261010120000 até
-- 20261015120000, mas este arquivo é ordenado antes da criação das tabelas
-- necessárias (por exemplo, public.asaas_charge_jobs). Em bancos novos isso
-- interrompia a aplicação completa do histórico.
--
-- Mantemos o identificador para compatibilidade com o histórico remoto. As
-- migrations canônicas de outubro, preservadas neste repositório, aplicam as
-- mesmas estruturas na ordem correta.
