-- Migration marker generated by the Lovable Cloud synchronization.
-- The canonical integration observability schema is applied by
-- 20261007120000_integration_observability.sql after all dependencies exist.

BEGIN;
COMMIT;
