-- FLUXA Financeiro: migration aditiva. O schema versionado foi auditado e não continha tabelas financeiras equivalentes.
CREATE TABLE IF NOT EXISTS public.financial_categories (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES public.organizations(id), name text NOT NULL,
 type text NOT NULL CHECK(type IN('income','expense','both')), description text, color text, is_active boolean NOT NULL DEFAULT true,
 created_by uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), archived_at timestamptz,
 UNIQUE(organization_id,name,type)
);
CREATE TABLE IF NOT EXISTS public.financial_accounts (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES public.organizations(id), name text NOT NULL,
 type text NOT NULL CHECK(type IN('cash','bank','digital_wallet','other')), description text, initial_balance numeric(14,2) NOT NULL DEFAULT 0 CHECK(initial_balance>=0),
 current_balance numeric(14,2) NOT NULL DEFAULT 0, is_active boolean NOT NULL DEFAULT true, created_by uuid NOT NULL,
 created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), archived_at timestamptz,
 UNIQUE(organization_id,name)
);
CREATE TABLE IF NOT EXISTS public.financial_recurrences (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES public.organizations(id), name text NOT NULL,
 type text NOT NULL CHECK(type IN('income','expense')), amount numeric(14,2) NOT NULL CHECK(amount>0), category_id uuid REFERENCES public.financial_categories(id), account_id uuid REFERENCES public.financial_accounts(id),
 frequency text NOT NULL CHECK(frequency IN('weekly','monthly','quarterly','yearly')), interval_count integer NOT NULL DEFAULT 1 CHECK(interval_count>0), start_date date NOT NULL, end_date date,
 next_run_date date NOT NULL, status text NOT NULL DEFAULT 'active' CHECK(status IN('active','paused','finished')), client_id uuid REFERENCES public.clients(id), process_id uuid REFERENCES public.processes(id), notes text,
 created_by uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), archived_at timestamptz, CHECK(end_date IS NULL OR end_date>=start_date)
);
CREATE TABLE IF NOT EXISTS public.financial_transactions (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES public.organizations(id), type text NOT NULL CHECK(type IN('income','expense')),
 description text NOT NULL CHECK(length(trim(description))>0), amount numeric(14,2) NOT NULL CHECK(amount>0), category_id uuid REFERENCES public.financial_categories(id), account_id uuid REFERENCES public.financial_accounts(id),
 status text NOT NULL DEFAULT 'pending' CHECK(status IN('pending','paid','overdue','cancelled','partial')), due_date date NOT NULL, paid_at timestamptz, competence_date date,
 payment_method text, client_id uuid REFERENCES public.clients(id), process_id uuid REFERENCES public.processes(id), task_id uuid REFERENCES public.tasks(id), document_id uuid REFERENCES public.documents(id),
 responsible_user_id uuid, notes text, reference text, recurrence_id uuid REFERENCES public.financial_recurrences(id), recurrence_due_date date,
 created_by uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), archived_at timestamptz,
 UNIQUE(recurrence_id,recurrence_due_date)
);
CREATE TABLE IF NOT EXISTS public.financial_transaction_payments (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES public.organizations(id), transaction_id uuid NOT NULL REFERENCES public.financial_transactions(id),
 amount numeric(14,2) NOT NULL CHECK(amount>0), paid_at timestamptz NOT NULL DEFAULT now(), payment_method text, account_id uuid NOT NULL REFERENCES public.financial_accounts(id), notes text,
 reversed_at timestamptz, reversal_notes text, created_by uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.financial_account_movements (
 id uuid PRIMARY KEY DEFAULT gen_random_uuid(), organization_id uuid NOT NULL REFERENCES public.organizations(id), account_id uuid NOT NULL REFERENCES public.financial_accounts(id),
 transaction_id uuid REFERENCES public.financial_transactions(id), payment_id uuid REFERENCES public.financial_transaction_payments(id), type text NOT NULL CHECK(type IN('income','expense','reversal')),
 amount numeric(14,2) NOT NULL CHECK(amount>0), balance_after numeric(14,2) NOT NULL, description text NOT NULL, created_by uuid NOT NULL, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS financial_transactions_filter_idx ON public.financial_transactions(organization_id,type,status,due_date) WHERE archived_at IS NULL;
CREATE INDEX IF NOT EXISTS financial_payments_transaction_idx ON public.financial_transaction_payments(transaction_id) WHERE reversed_at IS NULL;
CREATE INDEX IF NOT EXISTS financial_movements_account_idx ON public.financial_account_movements(organization_id,account_id,created_at DESC);

CREATE OR REPLACE FUNCTION public.financial_guard_immutable_org() RETURNS trigger LANGUAGE plpgsql SET search_path=public AS $$BEGIN IF NEW.organization_id<>OLD.organization_id THEN RAISE EXCEPTION 'ORGANIZATION_IMMUTABLE'; END IF; RETURN NEW; END$$;
CREATE OR REPLACE FUNCTION public.financial_validate_links() RETURNS trigger LANGUAGE plpgsql SET search_path=public AS $$BEGIN
 IF NEW.category_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.financial_categories x WHERE x.id=NEW.category_id AND x.organization_id=NEW.organization_id) THEN RAISE EXCEPTION 'INVALID_CATEGORY_ORGANIZATION'; END IF;
 IF NEW.account_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.financial_accounts x WHERE x.id=NEW.account_id AND x.organization_id=NEW.organization_id) THEN RAISE EXCEPTION 'INVALID_ACCOUNT_ORGANIZATION'; END IF;
 IF NEW.client_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.clients x WHERE x.id=NEW.client_id AND x.organization_id=NEW.organization_id) THEN RAISE EXCEPTION 'INVALID_CLIENT_ORGANIZATION'; END IF;
 IF NEW.process_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.processes x WHERE x.id=NEW.process_id AND x.organization_id=NEW.organization_id) THEN RAISE EXCEPTION 'INVALID_PROCESS_ORGANIZATION'; END IF;
 IF NEW.task_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.tasks x WHERE x.id=NEW.task_id AND x.organization_id=NEW.organization_id) THEN RAISE EXCEPTION 'INVALID_TASK_ORGANIZATION'; END IF;
 IF NEW.document_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.documents x WHERE x.id=NEW.document_id AND x.organization_id=NEW.organization_id) THEN RAISE EXCEPTION 'INVALID_DOCUMENT_ORGANIZATION'; END IF;
 IF NEW.responsible_user_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM public.organization_members x WHERE x.user_id=NEW.responsible_user_id AND x.organization_id=NEW.organization_id AND x.is_active) THEN RAISE EXCEPTION 'INVALID_RESPONSIBLE_ORGANIZATION'; END IF; RETURN NEW;
END$$;
DO $$DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['financial_categories','financial_accounts','financial_transactions','financial_transaction_payments','financial_recurrences','financial_account_movements'] LOOP EXECUTE format('DROP TRIGGER IF EXISTS financial_org_immutable ON public.%I; CREATE TRIGGER financial_org_immutable BEFORE UPDATE ON public.%I FOR EACH ROW EXECUTE FUNCTION public.financial_guard_immutable_org()',t,t); END LOOP; END$$;
DROP TRIGGER IF EXISTS financial_transaction_links ON public.financial_transactions; CREATE TRIGGER financial_transaction_links BEFORE INSERT OR UPDATE ON public.financial_transactions FOR EACH ROW EXECUTE FUNCTION public.financial_validate_links();
CREATE TRIGGER financial_categories_updated BEFORE UPDATE ON public.financial_categories FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER financial_accounts_updated BEFORE UPDATE ON public.financial_accounts FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER financial_transactions_updated BEFORE UPDATE ON public.financial_transactions FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER financial_recurrences_updated BEFORE UPDATE ON public.financial_recurrences FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.financial_categories ENABLE ROW LEVEL SECURITY; ALTER TABLE public.financial_accounts ENABLE ROW LEVEL SECURITY; ALTER TABLE public.financial_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.financial_transaction_payments ENABLE ROW LEVEL SECURITY; ALTER TABLE public.financial_recurrences ENABLE ROW LEVEL SECURITY; ALTER TABLE public.financial_account_movements ENABLE ROW LEVEL SECURITY;
CREATE POLICY financial_categories_read ON public.financial_categories FOR SELECT TO authenticated USING(public.is_org_member(organization_id));
CREATE POLICY financial_accounts_read ON public.financial_accounts FOR SELECT TO authenticated USING(public.has_org_role(organization_id,ARRAY['proprietario','administrador','gestor','visualizador']::public.app_role[]));
CREATE POLICY financial_transactions_read ON public.financial_transactions FOR SELECT TO authenticated USING(public.has_org_role(organization_id,ARRAY['proprietario','administrador','gestor','visualizador']::public.app_role[]) OR (public.has_org_role(organization_id,ARRAY['operacional']::public.app_role[]) AND (responsible_user_id=auth.uid() OR EXISTS(SELECT 1 FROM public.tasks t WHERE t.id=task_id AND t.assignee_id=auth.uid()) OR EXISTS(SELECT 1 FROM public.processes p WHERE p.id=process_id AND p.owner_id=auth.uid()) OR EXISTS(SELECT 1 FROM public.clients c WHERE c.id=client_id AND c.owner_id=auth.uid()))));
CREATE POLICY financial_payments_read ON public.financial_transaction_payments FOR SELECT TO authenticated USING(public.has_org_role(organization_id,ARRAY['proprietario','administrador','gestor','visualizador']::public.app_role[]));
CREATE POLICY financial_recurrences_read ON public.financial_recurrences FOR SELECT TO authenticated USING(public.has_org_role(organization_id,ARRAY['proprietario','administrador','gestor','visualizador']::public.app_role[]));
CREATE POLICY financial_movements_read ON public.financial_account_movements FOR SELECT TO authenticated USING(public.has_org_role(organization_id,ARRAY['proprietario','administrador','gestor','visualizador']::public.app_role[]));
REVOKE ALL ON public.financial_categories,public.financial_accounts,public.financial_transactions,public.financial_transaction_payments,public.financial_recurrences,public.financial_account_movements FROM PUBLIC,anon;
GRANT SELECT ON public.financial_categories,public.financial_accounts,public.financial_transactions,public.financial_transaction_payments,public.financial_recurrences,public.financial_account_movements TO authenticated;

CREATE OR REPLACE FUNCTION public.financial_assert_editor(_org uuid) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$BEGIN IF auth.uid() IS NULL THEN RAISE EXCEPTION 'AUTH_REQUIRED'; END IF; IF NOT public.has_org_role(_org,ARRAY['proprietario','administrador','gestor']::public.app_role[]) THEN RAISE EXCEPTION 'NOT_ALLOWED'; END IF; END$$;
CREATE OR REPLACE FUNCTION public.financial_audit(_org uuid,_action text,_entity text,_id uuid,_meta jsonb DEFAULT '{}'::jsonb) RETURNS void LANGUAGE sql SECURITY DEFINER SET search_path=public AS $$INSERT INTO public.audit_logs(organization_id,actor_id,actor_name,action,entity,entity_id,metadata) VALUES($1,auth.uid(),(SELECT full_name FROM public.profiles WHERE id=auth.uid()),$2,$3,$4,$5)$$;

CREATE OR REPLACE FUNCTION public.create_financial_transaction(_organization_id uuid,_payload jsonb) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$DECLARE v uuid;BEGIN PERFORM public.financial_assert_editor(_organization_id); IF NULLIF(trim(_payload->>'description'),'') IS NULL THEN RAISE EXCEPTION 'DESCRIPTION_REQUIRED'; END IF; IF NULLIF(_payload->>'type','') IS NULL OR _payload->>'type' NOT IN ('income','expense') THEN RAISE EXCEPTION 'INVALID_TRANSACTION_TYPE'; END IF; IF NULLIF(_payload->>'amount','') IS NULL OR NULLIF(_payload->>'amount','')::numeric<=0 THEN RAISE EXCEPTION 'INVALID_AMOUNT'; END IF; IF NULLIF(_payload->>'due_date','') IS NULL THEN RAISE EXCEPTION 'DUE_DATE_REQUIRED'; END IF; INSERT INTO public.financial_transactions(organization_id,type,description,amount,category_id,account_id,due_date,competence_date,payment_method,client_id,process_id,task_id,document_id,responsible_user_id,notes,reference,created_by) VALUES(_organization_id,_payload->>'type',trim(_payload->>'description'),(_payload->>'amount')::numeric,NULLIF(_payload->>'category_id','')::uuid,NULLIF(_payload->>'account_id','')::uuid,(_payload->>'due_date')::date,NULLIF(_payload->>'competence_date','')::date,_payload->>'payment_method',NULLIF(_payload->>'client_id','')::uuid,NULLIF(_payload->>'process_id','')::uuid,NULLIF(_payload->>'task_id','')::uuid,NULLIF(_payload->>'document_id','')::uuid,NULLIF(_payload->>'responsible_user_id','')::uuid,_payload->>'notes',_payload->>'reference',auth.uid()) RETURNING id INTO v; PERFORM public.financial_audit(_organization_id,'financial.transaction.created','financial_transaction',v); RETURN v;END$$;
CREATE OR REPLACE FUNCTION public.update_financial_transaction(_organization_id uuid,_payload jsonb) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$DECLARE v uuid:=(_payload->>'id')::uuid;BEGIN PERFORM public.financial_assert_editor(_organization_id); UPDATE public.financial_transactions SET description=COALESCE(_payload->>'description',description),amount=COALESCE(NULLIF(_payload->>'amount','')::numeric,amount),due_date=COALESCE(NULLIF(_payload->>'due_date','')::date,due_date),category_id=CASE WHEN _payload ? 'category_id' THEN NULLIF(_payload->>'category_id','')::uuid ELSE category_id END,account_id=CASE WHEN _payload ? 'account_id' THEN NULLIF(_payload->>'account_id','')::uuid ELSE account_id END,notes=COALESCE(_payload->>'notes',notes) WHERE id=v AND organization_id=_organization_id AND status IN('pending','overdue','partial') AND archived_at IS NULL; IF NOT FOUND THEN RAISE EXCEPTION 'TRANSACTION_NOT_EDITABLE'; END IF; PERFORM public.financial_audit(_organization_id,'financial.transaction.updated','financial_transaction',v);RETURN v;END$$;

CREATE OR REPLACE FUNCTION public.register_partial_payment(_organization_id uuid,_transaction_id uuid,_amount numeric,_account_id uuid,_payment_method text DEFAULT NULL,_notes text DEFAULT NULL) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$DECLARE t public.financial_transactions%ROWTYPE;a public.financial_accounts%ROWTYPE;total numeric;pid uuid;newbal numeric;BEGIN
 PERFORM public.financial_assert_editor(_organization_id); IF _amount<=0 THEN RAISE EXCEPTION 'INVALID_AMOUNT'; END IF;
 SELECT * INTO t FROM public.financial_transactions WHERE id=_transaction_id AND organization_id=_organization_id FOR UPDATE; IF NOT FOUND OR t.archived_at IS NOT NULL OR t.status='cancelled' THEN RAISE EXCEPTION 'TRANSACTION_NOT_PAYABLE'; END IF;
 SELECT COALESCE(sum(amount),0) INTO total FROM public.financial_transaction_payments WHERE transaction_id=t.id AND reversed_at IS NULL; IF _amount>t.amount-total THEN RAISE EXCEPTION 'PAYMENT_EXCEEDS_BALANCE'; END IF;
 SELECT * INTO a FROM public.financial_accounts WHERE id=_account_id AND organization_id=_organization_id AND archived_at IS NULL AND is_active FOR UPDATE; IF NOT FOUND THEN RAISE EXCEPTION 'ACCOUNT_NOT_AVAILABLE'; END IF;
 newbal:=a.current_balance+CASE WHEN t.type='income' THEN _amount ELSE -_amount END; UPDATE public.financial_accounts SET current_balance=newbal WHERE id=a.id;
 INSERT INTO public.financial_transaction_payments(organization_id,transaction_id,amount,payment_method,account_id,notes,created_by) VALUES(_organization_id,t.id,_amount,_payment_method,a.id,_notes,auth.uid()) RETURNING id INTO pid;
 INSERT INTO public.financial_account_movements(organization_id,account_id,transaction_id,payment_id,type,amount,balance_after,description,created_by) VALUES(_organization_id,a.id,t.id,pid,t.type,_amount,newbal,'Pagamento: '||t.description,auth.uid()); total:=total+_amount;
 UPDATE public.financial_transactions SET status=CASE WHEN total=t.amount THEN 'paid' ELSE 'partial' END,paid_at=CASE WHEN total=t.amount THEN now() ELSE NULL END,payment_method=COALESCE(_payment_method,payment_method),account_id=a.id WHERE id=t.id;
 PERFORM public.financial_audit(_organization_id,CASE WHEN total=t.amount THEN 'financial.payment.registered' ELSE 'financial.payment.partial' END,'financial_payment',pid,jsonb_build_object('amount',_amount,'transaction_id',t.id));RETURN pid;END$$;
CREATE OR REPLACE FUNCTION public.mark_financial_transaction_paid(_organization_id uuid,_transaction_id uuid,_account_id uuid,_payment_method text DEFAULT NULL) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$DECLARE remaining numeric;BEGIN SELECT t.amount-COALESCE(sum(p.amount) FILTER(WHERE p.reversed_at IS NULL),0) INTO remaining FROM public.financial_transactions t LEFT JOIN public.financial_transaction_payments p ON p.transaction_id=t.id WHERE t.id=_transaction_id AND t.organization_id=_organization_id GROUP BY t.amount; RETURN public.register_partial_payment(_organization_id,_transaction_id,remaining,_account_id,_payment_method,NULL);END$$;
CREATE OR REPLACE FUNCTION public.reverse_financial_payment(_organization_id uuid,_payment_id uuid,_notes text) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$DECLARE p public.financial_transaction_payments%ROWTYPE;t public.financial_transactions%ROWTYPE;a public.financial_accounts%ROWTYPE;newbal numeric;total numeric;BEGIN PERFORM public.financial_assert_editor(_organization_id); IF NOT public.has_org_role(_organization_id,ARRAY['proprietario','administrador']::public.app_role[]) THEN RAISE EXCEPTION 'NOT_ALLOWED'; END IF; SELECT * INTO p FROM public.financial_transaction_payments WHERE id=_payment_id AND organization_id=_organization_id AND reversed_at IS NULL FOR UPDATE; IF NOT FOUND THEN RAISE EXCEPTION 'PAYMENT_NOT_FOUND'; END IF; SELECT * INTO t FROM public.financial_transactions WHERE id=p.transaction_id FOR UPDATE; SELECT * INTO a FROM public.financial_accounts WHERE id=p.account_id FOR UPDATE;newbal:=a.current_balance+CASE WHEN t.type='income' THEN -p.amount ELSE p.amount END;UPDATE public.financial_accounts SET current_balance=newbal WHERE id=a.id;UPDATE public.financial_transaction_payments SET reversed_at=now(),reversal_notes=_notes WHERE id=p.id;INSERT INTO public.financial_account_movements(organization_id,account_id,transaction_id,payment_id,type,amount,balance_after,description,created_by) VALUES(_organization_id,a.id,t.id,p.id,'reversal',p.amount,newbal,'Estorno: '||t.description,auth.uid());SELECT COALESCE(sum(amount),0) INTO total FROM public.financial_transaction_payments WHERE transaction_id=t.id AND reversed_at IS NULL;UPDATE public.financial_transactions SET status=CASE WHEN total=0 THEN 'pending' ELSE 'partial' END,paid_at=NULL WHERE id=t.id;PERFORM public.financial_audit(_organization_id,'financial.payment.reversed','financial_payment',p.id);RETURN p.id;END$$;

CREATE OR REPLACE FUNCTION public.cancel_financial_transaction(_organization_id uuid,_payload jsonb) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$DECLARE v uuid:=(_payload->>'id')::uuid;BEGIN PERFORM public.financial_assert_editor(_organization_id);IF EXISTS(SELECT 1 FROM public.financial_transaction_payments WHERE transaction_id=v AND reversed_at IS NULL) THEN RAISE EXCEPTION 'REVERSE_PAYMENTS_FIRST';END IF;UPDATE public.financial_transactions SET status='cancelled' WHERE id=v AND organization_id=_organization_id AND archived_at IS NULL;IF NOT FOUND THEN RAISE EXCEPTION 'NOT_FOUND';END IF;PERFORM public.financial_audit(_organization_id,'financial.transaction.cancelled','financial_transaction',v);RETURN v;END$$;
CREATE OR REPLACE FUNCTION public.archive_financial_transaction(_organization_id uuid,_payload jsonb) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$DECLARE v uuid:=(_payload->>'id')::uuid;BEGIN PERFORM public.financial_assert_editor(_organization_id);UPDATE public.financial_transactions SET archived_at=now() WHERE id=v AND organization_id=_organization_id AND status IN('paid','cancelled');IF NOT FOUND THEN RAISE EXCEPTION 'TRANSACTION_NOT_ARCHIVABLE';END IF;PERFORM public.financial_audit(_organization_id,'financial.transaction.archived','financial_transaction',v);RETURN v;END$$;
CREATE OR REPLACE FUNCTION public.duplicate_financial_transaction(_organization_id uuid,_payload jsonb) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$DECLARE v uuid;t public.financial_transactions%ROWTYPE;BEGIN PERFORM public.financial_assert_editor(_organization_id);SELECT * INTO t FROM public.financial_transactions WHERE id=(_payload->>'id')::uuid AND organization_id=_organization_id;INSERT INTO public.financial_transactions(organization_id,type,description,amount,category_id,account_id,status,due_date,competence_date,client_id,process_id,task_id,document_id,responsible_user_id,notes,reference,created_by) VALUES(_organization_id,t.type,t.description||' (cópia)',t.amount,t.category_id,t.account_id,'pending',COALESCE(NULLIF(_payload->>'due_date','')::date,t.due_date),t.competence_date,t.client_id,t.process_id,t.task_id,t.document_id,t.responsible_user_id,t.notes,t.reference,auth.uid()) RETURNING id INTO v;PERFORM public.financial_audit(_organization_id,'financial.transaction.duplicated','financial_transaction',v);RETURN v;END$$;
CREATE OR REPLACE FUNCTION public.create_financial_category(_organization_id uuid,_payload jsonb) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$DECLARE v uuid;BEGIN PERFORM public.financial_assert_editor(_organization_id);IF NULLIF(trim(_payload->>'name'),'') IS NULL THEN RAISE EXCEPTION 'NAME_REQUIRED';END IF;IF NULLIF(_payload->>'type','') IS NULL OR _payload->>'type' NOT IN ('income','expense','both') THEN RAISE EXCEPTION 'INVALID_CATEGORY_TYPE';END IF;INSERT INTO public.financial_categories(organization_id,name,type,description,color,created_by) VALUES(_organization_id,trim(_payload->>'name'),_payload->>'type',_payload->>'description',_payload->>'color',auth.uid()) RETURNING id INTO v;PERFORM public.financial_audit(_organization_id,'financial.category.created','financial_category',v);RETURN v;END$$;
CREATE OR REPLACE FUNCTION public.update_financial_category(_organization_id uuid,_payload jsonb) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$DECLARE v uuid:=(_payload->>'id')::uuid;BEGIN PERFORM public.financial_assert_editor(_organization_id);UPDATE public.financial_categories SET name=COALESCE(_payload->>'name',name),type=COALESCE(_payload->>'type',type),description=COALESCE(_payload->>'description',description),color=COALESCE(_payload->>'color',color) WHERE id=v AND organization_id=_organization_id AND archived_at IS NULL;IF NOT FOUND THEN RAISE EXCEPTION 'NOT_FOUND';END IF;PERFORM public.financial_audit(_organization_id,'financial.category.updated','financial_category',v);RETURN v;END$$;
CREATE OR REPLACE FUNCTION public.set_financial_category_active(_organization_id uuid,_payload jsonb) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$DECLARE v uuid:=(_payload->>'id')::uuid;BEGIN PERFORM public.financial_assert_editor(_organization_id);UPDATE public.financial_categories SET is_active=(_payload->>'is_active')::boolean WHERE id=v AND organization_id=_organization_id AND archived_at IS NULL;RETURN v;END$$;
CREATE OR REPLACE FUNCTION public.archive_financial_category(_organization_id uuid,_payload jsonb) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$DECLARE v uuid:=(_payload->>'id')::uuid;BEGIN PERFORM public.financial_assert_editor(_organization_id);IF EXISTS(SELECT 1 FROM public.financial_transactions WHERE category_id=v AND archived_at IS NULL) AND COALESCE(NULLIF(_payload->>'confirmed','')::boolean,false)=false THEN RAISE EXCEPTION 'CATEGORY_IN_USE_CONFIRM_REQUIRED';END IF;UPDATE public.financial_categories SET archived_at=now(),is_active=false WHERE id=v AND organization_id=_organization_id;PERFORM public.financial_audit(_organization_id,'financial.category.archived','financial_category',v);RETURN v;END$$;
CREATE OR REPLACE FUNCTION public.create_financial_account(_organization_id uuid,_payload jsonb) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$DECLARE v uuid;b numeric:=COALESCE(NULLIF(_payload->>'initial_balance','')::numeric,0);BEGIN PERFORM public.financial_assert_editor(_organization_id);IF NULLIF(trim(_payload->>'name'),'') IS NULL THEN RAISE EXCEPTION 'NAME_REQUIRED';END IF;IF NULLIF(_payload->>'type','') IS NULL OR _payload->>'type' NOT IN ('cash','bank','digital_wallet','other') THEN RAISE EXCEPTION 'INVALID_ACCOUNT_TYPE';END IF;IF b<0 THEN RAISE EXCEPTION 'INVALID_INITIAL_BALANCE';END IF;INSERT INTO public.financial_accounts(organization_id,name,type,description,initial_balance,current_balance,created_by) VALUES(_organization_id,trim(_payload->>'name'),_payload->>'type',_payload->>'description',b,b,auth.uid()) RETURNING id INTO v;PERFORM public.financial_audit(_organization_id,'financial.account.created','financial_account',v);RETURN v;END$$;
CREATE OR REPLACE FUNCTION public.update_financial_account(_organization_id uuid,_payload jsonb) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$DECLARE v uuid:=(_payload->>'id')::uuid;BEGIN PERFORM public.financial_assert_editor(_organization_id);UPDATE public.financial_accounts SET name=COALESCE(_payload->>'name',name),type=COALESCE(_payload->>'type',type),description=COALESCE(_payload->>'description',description) WHERE id=v AND organization_id=_organization_id AND archived_at IS NULL;IF NOT FOUND THEN RAISE EXCEPTION 'NOT_FOUND';END IF;PERFORM public.financial_audit(_organization_id,'financial.account.updated','financial_account',v);RETURN v;END$$;
CREATE OR REPLACE FUNCTION public.set_financial_account_active(_organization_id uuid,_payload jsonb) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$DECLARE v uuid:=(_payload->>'id')::uuid;BEGIN PERFORM public.financial_assert_editor(_organization_id);UPDATE public.financial_accounts SET is_active=(_payload->>'is_active')::boolean WHERE id=v AND organization_id=_organization_id AND archived_at IS NULL;RETURN v;END$$;
CREATE OR REPLACE FUNCTION public.archive_financial_account(_organization_id uuid,_payload jsonb) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$DECLARE v uuid:=(_payload->>'id')::uuid;BEGIN PERFORM public.financial_assert_editor(_organization_id);IF EXISTS(SELECT 1 FROM public.financial_transactions WHERE account_id=v AND archived_at IS NULL AND status IN('pending','partial','overdue')) THEN RAISE EXCEPTION 'ACCOUNT_HAS_OPEN_TRANSACTIONS';END IF;UPDATE public.financial_accounts SET archived_at=now(),is_active=false WHERE id=v AND organization_id=_organization_id;PERFORM public.financial_audit(_organization_id,'financial.account.archived','financial_account',v);RETURN v;END$$;
CREATE OR REPLACE FUNCTION public.create_financial_recurrence(_organization_id uuid,_payload jsonb) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$DECLARE v uuid;BEGIN PERFORM public.financial_assert_editor(_organization_id);IF NULLIF(trim(_payload->>'name'),'') IS NULL THEN RAISE EXCEPTION 'NAME_REQUIRED';END IF;IF NULLIF(_payload->>'type','') IS NULL OR _payload->>'type' NOT IN ('income','expense') THEN RAISE EXCEPTION 'INVALID_RECURRENCE_TYPE';END IF;IF NULLIF(_payload->>'amount','') IS NULL OR NULLIF(_payload->>'amount','')::numeric<=0 THEN RAISE EXCEPTION 'INVALID_AMOUNT';END IF;IF NULLIF(_payload->>'frequency','') IS NULL OR _payload->>'frequency' NOT IN ('weekly','monthly','quarterly','yearly') THEN RAISE EXCEPTION 'INVALID_FREQUENCY';END IF;IF NULLIF(_payload->>'start_date','') IS NULL THEN RAISE EXCEPTION 'START_DATE_REQUIRED';END IF;INSERT INTO public.financial_recurrences(organization_id,name,type,amount,category_id,account_id,frequency,interval_count,start_date,end_date,next_run_date,client_id,process_id,notes,created_by) VALUES(_organization_id,_payload->>'name',_payload->>'type',(_payload->>'amount')::numeric,NULLIF(_payload->>'category_id','')::uuid,NULLIF(_payload->>'account_id','')::uuid,_payload->>'frequency',COALESCE(NULLIF(_payload->>'interval_count','')::integer,1),(_payload->>'start_date')::date,NULLIF(_payload->>'end_date','')::date,COALESCE(NULLIF(_payload->>'next_run_date','')::date,(_payload->>'start_date')::date),NULLIF(_payload->>'client_id','')::uuid,NULLIF(_payload->>'process_id','')::uuid,_payload->>'notes',auth.uid()) RETURNING id INTO v;PERFORM public.financial_audit(_organization_id,'financial.recurrence.created','financial_recurrence',v);RETURN v;END$$;
CREATE OR REPLACE FUNCTION public.update_financial_recurrence(_organization_id uuid,_payload jsonb) RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$DECLARE v uuid:=(_payload->>'id')::uuid;BEGIN PERFORM public.financial_assert_editor(_organization_id);UPDATE public.financial_recurrences SET name=COALESCE(NULLIF(trim(_payload->>'name'),''),name),amount=COALESCE(NULLIF(_payload->>'amount','')::numeric,amount),status=COALESCE(NULLIF(_payload->>'status',''),status),category_id=CASE WHEN _payload ? 'category_id' THEN NULLIF(_payload->>'category_id','')::uuid ELSE category_id END,account_id=CASE WHEN _payload ? 'account_id' THEN NULLIF(_payload->>'account_id','')::uuid ELSE account_id END,client_id=CASE WHEN _payload ? 'client_id' THEN NULLIF(_payload->>'client_id','')::uuid ELSE client_id END,process_id=CASE WHEN _payload ? 'process_id' THEN NULLIF(_payload->>'process_id','')::uuid ELSE process_id END,end_date=CASE WHEN _payload ? 'end_date' THEN NULLIF(_payload->>'end_date','')::date ELSE end_date END,next_run_date=COALESCE(NULLIF(_payload->>'next_run_date','')::date,next_run_date),notes=COALESCE(_payload->>'notes',notes) WHERE id=v AND organization_id=_organization_id AND archived_at IS NULL;IF NOT FOUND THEN RAISE EXCEPTION 'NOT_FOUND';END IF;PERFORM public.financial_audit(_organization_id,'financial.recurrence.updated','financial_recurrence',v);RETURN v;END$$;
CREATE OR REPLACE FUNCTION public.generate_recurrence_transactions(_organization_id uuid,_payload jsonb) RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$DECLARE r public.financial_recurrences%ROWTYPE;until_date date:=COALESCE(NULLIF(_payload->>'until','')::date,current_date);run_date date;generated integer:=0;BEGIN PERFORM public.financial_assert_editor(_organization_id);FOR r IN SELECT * FROM public.financial_recurrences WHERE organization_id=_organization_id AND status='active' AND archived_at IS NULL AND next_run_date<=until_date FOR UPDATE LOOP run_date:=r.next_run_date;WHILE run_date<=until_date AND (r.end_date IS NULL OR run_date<=r.end_date) LOOP INSERT INTO public.financial_transactions(organization_id,type,description,amount,category_id,account_id,due_date,competence_date,client_id,process_id,notes,recurrence_id,recurrence_due_date,created_by) VALUES(_organization_id,r.type,r.name,r.amount,r.category_id,r.account_id,run_date,run_date,r.client_id,r.process_id,r.notes,r.id,run_date,auth.uid()) ON CONFLICT(recurrence_id,recurrence_due_date) DO NOTHING;IF FOUND THEN generated:=generated+1;END IF;run_date:=CASE r.frequency WHEN 'weekly' THEN run_date+(7*r.interval_count) WHEN 'monthly' THEN run_date+make_interval(months=>r.interval_count) WHEN 'quarterly' THEN run_date+make_interval(months=>3*r.interval_count) ELSE run_date+make_interval(years=>r.interval_count) END;END LOOP;UPDATE public.financial_recurrences SET next_run_date=run_date,status=CASE WHEN end_date IS NOT NULL AND run_date>end_date THEN 'finished' ELSE status END WHERE id=r.id;END LOOP;PERFORM public.financial_audit(_organization_id,'financial.recurrence.generated','financial_recurrence',NULL,jsonb_build_object('count',generated));RETURN generated;END$$;

-- Somente RPCs podem escrever; nenhuma tabela financeira concede INSERT/UPDATE/DELETE ao frontend.
REVOKE EXECUTE ON FUNCTION public.financial_assert_editor(uuid),public.financial_audit(uuid,text,text,uuid,jsonb) FROM PUBLIC,anon,authenticated;
DO $$DECLARE f record;BEGIN FOR f IN SELECT p.oid::regprocedure sig FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname IN('create_financial_transaction','update_financial_transaction','mark_financial_transaction_paid','register_partial_payment','cancel_financial_transaction','duplicate_financial_transaction','archive_financial_transaction','create_financial_category','update_financial_category','set_financial_category_active','archive_financial_category','create_financial_account','update_financial_account','set_financial_account_active','archive_financial_account','create_financial_recurrence','update_financial_recurrence','generate_recurrence_transactions','reverse_financial_payment') LOOP EXECUTE format('REVOKE EXECUTE ON FUNCTION %s FROM PUBLIC, anon',f.sig);EXECUTE format('GRANT EXECUTE ON FUNCTION %s TO authenticated',f.sig);END LOOP;END$$;
REVOKE DELETE ON public.financial_categories,public.financial_accounts,public.financial_transactions,public.financial_transaction_payments,public.financial_recurrences,public.financial_account_movements FROM authenticated,PUBLIC,anon;
