-- Integração posterior à migration do Monitoramento; preserva nome e colunas da view/RPCs.
DROP VIEW IF EXISTS public.operational_monitoring_alerts;
CREATE VIEW public.operational_monitoring_alerts WITH (security_invoker=true) AS
WITH alerts AS (
 SELECT t.organization_id,'tarefa'::text source_type,t.id source_id,CASE WHEN t.due_at::date<current_date THEN 'tarefa_atrasada' WHEN t.due_at::date=current_date THEN 'tarefa_hoje' ELSE 'tarefa_proxima' END alert_kind,t.title,t.description,t.client_id,t.process_id,t.assignee_id responsible_id,t.assignee_name responsible_name,t.priority::text source_priority,t.due_at relevant_at,t.updated_at last_movement_at,(t.due_at::date-current_date)::int days_delta,t.status::text source_status,NULL::numeric amount FROM public.tasks t WHERE t.archived_at IS NULL AND t.deleted_at IS NULL AND t.completed_at IS NULL AND t.status NOT IN ('concluida','cancelada') AND t.due_at::date<=current_date+COALESCE((SELECT s.monitoring_upcoming_days FROM public.organization_settings s WHERE s.organization_id=t.organization_id),7)
 UNION ALL SELECT p.organization_id,'processo',p.id,CASE WHEN p.due_date<current_date THEN 'processo_atrasado' WHEN p.due_date<=current_date+COALESCE((SELECT s.monitoring_upcoming_days FROM public.organization_settings s WHERE s.organization_id=p.organization_id),7) THEN 'processo_prazo_proximo' ELSE 'processo_sem_movimentacao' END,COALESCE(p.title,p.code),NULL,p.client_id,p.id,p.owner_id,p.owner_name,p.priority::text,p.due_date::timestamptz,p.last_movement_at,(p.due_date-current_date)::int,p.stage::text,NULL FROM public.processes p WHERE p.archived_at IS NULL AND (p.due_date<=current_date+COALESCE((SELECT s.monitoring_upcoming_days FROM public.organization_settings s WHERE s.organization_id=p.organization_id),7) OR p.last_movement_at<now()-make_interval(days=>COALESCE((SELECT s.stale_process_days FROM public.organization_settings s WHERE s.organization_id=p.organization_id),14)))
 UNION ALL SELECT d.organization_id,'documento',d.id,CASE WHEN d.expiration_date<current_date THEN 'documento_vencido' ELSE 'documento_vencendo' END,d.title,d.description,d.client_id,d.process_id,NULL,d.uploaded_by_name,NULL,d.expiration_date::timestamptz,d.updated_at,(d.expiration_date-current_date)::int,d.status::text,NULL FROM public.documents d WHERE d.archived_at IS NULL AND d.expiration_date IS NOT NULL AND COALESCE((SELECT s.monitoring_show_documents FROM public.organization_settings s WHERE s.organization_id=d.organization_id),true) AND d.expiration_date<=current_date+COALESCE((SELECT s.monitoring_document_expiration_days FROM public.organization_settings s WHERE s.organization_id=d.organization_id),30)
 UNION ALL SELECT c.organization_id,'comunicacao',c.id,CASE WHEN c.follow_up_at<now() AND c.follow_up_at::date<current_date THEN 'retorno_atrasado' ELSE 'retorno_hoje' END,c.subject,NULL,c.client_id,c.process_id,c.assigned_to,NULL,c.priority::text,c.follow_up_at,c.updated_at,(c.follow_up_at::date-current_date)::int,c.status::text,NULL FROM public.communication_threads c WHERE c.archived_at IS NULL AND c.status NOT IN ('resolvida','arquivada') AND c.follow_up_at IS NOT NULL AND COALESCE((SELECT s.monitoring_show_communication FROM public.organization_settings s WHERE s.organization_id=c.organization_id),true) AND c.follow_up_at::date<=current_date
 UNION ALL SELECT f.organization_id,'financeiro',f.id,CASE WHEN f.due_date<current_date THEN 'financeiro_vencido' ELSE 'financeiro_proximo' END,f.description,f.notes,f.client_id,f.process_id,f.responsible_user_id,NULL,NULL,f.due_date::timestamptz,f.updated_at,(f.due_date-current_date)::int,f.status::text,GREATEST(f.amount-COALESCE((SELECT sum(fp.amount) FROM public.financial_transaction_payments fp WHERE fp.transaction_id=f.id AND fp.reversed_at IS NULL),0),0) FROM public.financial_transactions f WHERE f.archived_at IS NULL AND f.status IN ('pending','partial','overdue') AND COALESCE((SELECT s.monitoring_show_financial FROM public.organization_settings s WHERE s.organization_id=f.organization_id),true) AND f.due_date<=current_date+COALESCE((SELECT s.financial_alert_days FROM public.organization_settings s WHERE s.organization_id=f.organization_id),7)
), enriched AS (SELECT a.*,c.name client_name,p.code process_code,CASE WHEN a.days_delta<=-7 OR a.source_priority IN ('urgente','critica') OR a.amount>=COALESCE((SELECT s.monitoring_financial_critical_threshold FROM public.organization_settings s WHERE s.organization_id=a.organization_id),50000) THEN 'critica' WHEN a.days_delta<0 OR a.source_priority='alta' OR a.amount>=COALESCE((SELECT s.monitoring_financial_high_threshold FROM public.organization_settings s WHERE s.organization_id=a.organization_id),10000) THEN 'alta' WHEN a.days_delta<=7 THEN 'media' ELSE 'baixa' END suggested_priority FROM alerts a LEFT JOIN public.clients c ON c.id=a.client_id AND c.organization_id=a.organization_id LEFT JOIN public.processes p ON p.id=a.process_id AND p.organization_id=a.organization_id)
SELECT e.organization_id,e.source_type,e.source_id,e.alert_kind,e.title,e.description,e.client_id,e.client_name,e.process_id,e.process_code,e.responsible_id,e.responsible_name,e.source_priority,e.suggested_priority,e.relevant_at,e.last_movement_at,e.days_delta,
 CASE WHEN e.alert_kind='processo_sem_movimentacao' THEN 'Processo sem movimentação há '||abs(extract(day from now()-e.last_movement_at))::int||' dias' WHEN e.days_delta<0 THEN e.title||' em atraso há '||abs(e.days_delta)||' dias' WHEN e.days_delta=0 THEN e.title||' vence hoje' ELSE e.title||' vence em '||e.days_delta||' dias' END reason,e.source_status,
 COALESCE(s.monitoring_status,'novo') monitoring_status,s.assigned_to,pr.full_name assigned_name,s.priority_override,s.notes,s.updated_at state_updated_at
FROM enriched e LEFT JOIN public.monitoring_states s ON s.organization_id=e.organization_id AND s.source_type=e.source_type AND s.source_id=e.source_id AND s.alert_kind=e.alert_kind LEFT JOIN public.profiles pr ON pr.id=s.assigned_to;

REVOKE ALL ON public.operational_monitoring_alerts FROM PUBLIC,anon; GRANT SELECT ON public.operational_monitoring_alerts TO authenticated;