-- Intentionally left as a no-op.
--
-- This migration duplicated 20260810180000_help_support_center.sql in full.
-- The schema, RLS policy, functions, and privileges are already established by
-- that earlier migration, so repeating them would fail on support_requests and
-- would not introduce any additional production behavior.
