-- Migration marker generated by the Lovable Cloud synchronization.
-- The canonical integration resilience schema is applied by
-- 20261006120000_integration_resilience.sql after all dependencies exist.

BEGIN;
COMMIT;
