-- Migration marker generated by the Lovable Cloud synchronization.
-- The canonical integration health schema is applied by
-- 20261005120000_integration_health_center.sql after all dependencies exist.

BEGIN;
COMMIT;
