-- Intentionally empty.
--
-- This migration was generated after the Help and Support module had already
-- been introduced by 20260810180000_help_support_center.sql. Keeping the file
-- preserves the migration version recorded in production, while avoiding a
-- second attempt to create public.support_requests during a clean db reset.
